BirthdayResearch/defichain-wallet

.github/workflows/stale.yml
CONTRIBUTING.md
README.md
translations/index.ts

/kind docs
Updated `README.md` and `CONTRIBUTING.md`, the front matters of developer contributing to DeFi Fiber project.

updated README.md and CONTRIBUTING.md

---

.github/workflows/oss-governance-project.yml

fix oss-governance-project not to trigger for bot

---

.github/workflows/ci.yml
.github/workflows/defichain-dependencies.yml
.github/workflows/stale.yml
.github/workflows/sync-labels.yml
app.json

fix github actions to a commit sha

---

.github/workflows/expo-preview.yml
.github/workflows/expo-publish.yml
CONTRIBUTING.md
app.json

/kind chore
1. expo preview build on PR
2. expo preview release on main publish

added expo-preview.yml and expo-publish.yml

---

README.md

fix Maintainability badge

---

.github/workflows/oss-governance-bot.yml
.github/workflows/oss-governance-labeler.yml
.github/workflows/oss-governance-project.yml
.github/workflows/sync-labels.yml

/kind chore
- Fixed all workflow actions version to a commit SHA.
- Added self-assign workflow

updated & cleanup `.github/workflows`

---

.github/workflows/ci.yml
.github/workflows/defichain-dependencies.yml
.github/workflows/expo-preview.yml
.github/workflows/expo-publish.yml
netlify.toml
package-lock.json
package.json

/kind chore
- Added netlify for UI Preview.
- Also revert to use node 14.x instead.

added netlify rich preview

---

.idea/codeStyles/Project.xml

.idea codeStyles to match ts-standard

---

.github/workflows/ci.yml
README.md
cypress.json
cypress/integration/functional/example.spec.ts
cypress/plugins/index.ts
cypress/support/commands.ts
cypress/support/index.ts
jest.config.js
package-lock.json
package.json
tsconfig.json

/kind chore
1. Setup Preview UI with Netlify
2. Setup E2E testing on `expo:web` using cypress as test runner
Fixes #6 and fixes #7

setup cypress for e2e testing

---

.github/workflows/oss-governance-project-issue.yml
.github/workflows/oss-governance-project-pr.yml
.github/workflows/oss-governance-project.yml
README.md

added workflow to automate adding issue

---

.github/workflows/oss-governance-project-issue.yml
.github/workflows/oss-governance-project-pr.yml

/kind chore
Convert governance automation script for project to use `actions/github-script`

convert governance automation script to use actions/github-script

---

App.web.tsx
navigation/BottomTabNavigator.tsx
screens/BalancesScreen/BalancesScreen.tsx
screens/LiquidityScreen/LiquidityScreen.tsx
screens/SettingsScreen/SettingsScreen.tsx
screens/TransactionsScreen/TransactionsScreen.tsx

/kind chore
Initial alternative web build setup for web preview. The playground will be incorporated with #9.
Web preview compiles React Native into Web with customized playground features for the community to try DeFi Wallet without running it on their phone. (There is a mobile preview too, see comment by @defichain-bot)
Playground is a specialized environment where blocks are minted every second, fake tDFI/tBTC/tETH/tUSDT is available for anyone to test DeFi protocols without using real assets.

initial setup for web preview & playground

---

.github/workflows/defichain-dependencies.yml
package-lock.json
package.json

added @defichain/* deps required for light-wallet

---

cypress/integration/functional/example.spec.ts

updated to a reasonable viewport for cypress

---

.github/workflows/expo-preview.yml

expo-preview will not run on bot PR

---

package-lock.json
package.json

Following https://github.com/DeFiCh/wallet/pull/81 direction, to match react-dom.

bump down react version to 16.13.1

---

.github/CODEOWNERS
.github/governance.yml
.github/labeler.yml
.github/labels.yml
store/index.ts

/kind chore
- For automated PR code review assignment
- Automate tagging of change for release

update governance with new project structure

---

.github/workflows/expo-dependencies.yml

/kind chore
workflow to update expo dependencies
Fixes #96

workflow to update expo dependencies

---

package-lock.json
package.json
store/liquidity.ts

/kind chore
Add `reselect` package. Enables composable selectors for redux
Fixes #

Add `reselect` package

---

package-lock.json
package.json
store/liquidity.ts

Removed reselect, its already included in `@reduxjs/toolkit`.

removed reselect deps

---

.idea/dictionaries/fuxing.xml
docker-compose.yml
hooks/api/usePlaygroundClient.ts
hooks/design/useColorScheme.ts
playground/Sections/Playground.Connection.tsx

updated playground to latest version

---

.github/workflows/ci.yml
docker-compose.yml
hooks/api/useNetwork.ts
playground/Sections/Playground.Connection.tsx

/kind chore
Refactor playground to use updated API.

updated playground to use new API

---

constants/Colors.ts
screens/WalletNavigator/BottomTabNavigator.tsx

/kind chore
Added PrimaryColor `#ff00af` to app.

added PrimaryColor for App

---

.github/workflows/translations-reporter.yml

/kind chore
`translations-reporter.yml` to automatically collapse into a `<details>` markdown.

updated translations-reporter.yml to collapse automatically

---

components/icons/tokens/_index.test.tsx
cypress/integration/functional/setting.spec.ts
playground/Sections/Playground.Connection.tsx
screens/WalletNavigator/BottomTabNavigator.tsx
screens/WalletNavigator/screens/SettingsScreen/SettingsNavigator.tsx
screens/WalletNavigator/screens/SettingsScreen/SettingsScreen.tsx
screens/WalletSetupNavigator/screens/WalletSetupScreen.tsx

/kind feature
Implemented settings page.
1. Network switcher will not be enabled in early builds as it will all point to the playground for now.
2. Security will be implemented in #57 
3. All advanced options are not compatible with the light implementation
4. Language is a system-level protocol, so we are not implementing that. We will let the OS handle that.
Help & Support is wasn't present when I worked on this screen. Please open another ticket for that.
Please note that screens look different on each platform.
Fixes #56

`Settings` UI Implementation 

---

.github/CODEOWNERS
.idea/dictionaries/fuxing.xml

updated code owners to include new maintainer

---

.github/workflows/oss-governance-project-pr.yml
.idea/dictionaries/fuxing.xml
playground/Sections/Playground.UTXO.tsx

Refactor PlaygroundAction to only show up if there is connection

---

CONTRIBUTING.md
cypress.json
package-lock.json
package.json

/kind chore
1. Updated viewport to 1000x800 (with Playground screen)
2. Added retries option in case there's an intermittent issue
3. Updated Cypress to v7.5.0
Fixes #

Cypress package update, added references in docs

---

.github/labeler.yml

/kind chore
bad indentation of a mapping entry

Fix bad indentation in labeler.yml

---

components/index.tsx
screens/AppNavigator/BottomTabNavigator.tsx
screens/AppNavigator/screens/SettingsScreen/SettingsScreen.tsx
screens/WalletNavigator/WalletNavigator.tsx
screens/WalletNavigator/screens/WalletMnemonicCreate.tsx
screens/WalletNavigator/screens/WalletMnemonicCreateVerify.tsx
screens/WalletNavigator/screens/WalletMnemonicRestore.tsx
screens/WalletNavigator/screens/WalletOnboarding.tsx

/kind chore
- Added components/index for default text/view/input with larger text size
- Removed title for bottom tab bar
- Removed Top NavBar back title

design changes text, bottom tab bar, top nav bar

---

playground/Playground.Action.tsx
playground/Playground.tsx
playground/Sections/Playground.Connection.tsx
playground/Sections/Playground.Token.tsx
playground/Sections/Playground.UTXO.tsx
playground/Sections/Playground.Wallet.tsx
screens/AppNavigator/AppNavigator.tsx
screens/AppNavigator/BottomTabNavigator.tsx
screens/AppNavigator/screens/BalancesScreen/BalancesScreen.tsx
screens/AppNavigator/screens/SettingsScreen/SettingsNavigator.tsx
screens/AppNavigator/screens/SettingsScreen/SettingsScreen.tsx
screens/Main.web.tsx

/kind feature
Debug tools for preview testing and preview QOL.
1. You can wallet setup by holding down the wallet icon for 5 seconds.
2. You can access the playground within settings by clicking on the playground.
Also made text in Playground larger, so that it's easier to see for testing.

Playground access within Settings

---

.github/ISSUE_TEMPLATE/5-translation-improvements.md

Added issue template for `translation improvements`

---

.idea/wallet.iml

/kind chore
Easier and faster to find {translate('', '')} for code editing QOL.

ignore __snapshot__ from source code search

---

.github/workflows/expo-publish.yml
.github/workflows/release-publish.yml
.versionrc.js
app.json
eas.json
package-lock.json
package.json

/kind chore
fixes #67
- Automate multiple release channels
- main branch
- pull request = preview
- prerelease = staging (kind of)
- release = production
- Automate native app building on release to Android & iOS
- Automate native app publishing on release to Android & iOS

expo EAS build & submit workflow

---

cypress.json
cypress/support/index.ts

/kind chore
- disabled logging for playground/info and playground/wallet
- disabled retries for openMode

configured cypress for better testing QOL

---

jest.config.js

/kind chore
Removed `playground` directory from code coverage
Fixes #

don't collect coverage from `playground` directory

---

.github/workflows/defichain-dependencies.yml

improved defichain-dependencies.yml

---

.github/workflows/defichain-dependencies.yml

improved @defichain/* update workflow

---

cypress/integration/functional/balances.spec.ts
playground/Sections/Playground.Token.tsx
playground/Sections/Playground.UTXO.tsx

/kind chore
Reduced top-up amount from 50 and 100 to just 100. 100 drains the global balances too quickly.

reduced playground top up amount to 10

---

.github/workflows/expo-preview.yml
.github/workflows/expo-publish.yml
.github/workflows/release-publish.yml

fix expo-actions as expo-token should be token

---

cypress/integration/functional/balances.spec.ts
cypress/integration/functional/transaction/list.spec.ts
cypress/support/commands.ts
screens/AppNavigator/screens/BalancesScreen/BalancesScreen.test.tsx
screens/AppNavigator/screens/BalancesScreen/BalancesScreen.tsx
screens/AppNavigator/screens/BalancesScreen/ReceiveScreen/ReceiveScreen.tsx
screens/AppNavigator/screens/BalancesScreen/__snapshots__/BalancesScreen.test.tsx.snap
store/wallet.test.ts
store/wallet.ts

/kind feature
1. Split token and UTXO DFI
2. Created `sendDFItoWallet` and `sendTokenToWallet` cypress commands for sending tokens to wallet
Fixes #

`balances` - split token and utxo DFI

---

.github/workflows/ci.yml
docker-compose.yml
package-lock.json
package.json

Bump whale & playground to 0.5.0 with actuator changes

---

.github/workflows/expo-dependencies.yml

/kind chore
Bump `expo-cli` in `expo-dependencies.yml` workflow.

Bump expo-cli in expo-dependencies.yml workflow

---

package-lock.json
package.json

/kind chore
Bump expo-cli version
Fixes #

bump expo-cli

---

.gitattributes
.github/CODEOWNERS
.github/governance.yml
.github/labeler.yml
.github/labels.yml
.idea/dictionaries/fuxing.xml
README.md

/kind docs
- Updated CODEOWNERS, governance and `.github/*` with new project structure
- Updated `README.md` with 
- project structure
- releases environment
- testing

Updated `README.md` with project narrative

---

App.tsx
app/logging.test.ts
app/logging.ts

/kind feature
Catch and log everything that needs to be caught or logged for centralized logging.

added `logging.ts` for centralized logging collecting and reporting

---

App.tsx
_shim.js

/kind fix
Fixed `Buffer` not found issues as `_shim.js` must be imported before any reference. Optimize import reshuffled that import previously. Added `_` prefix to prevent it from reshuffling below.

fixed shim ordering breaking Buffer polyfill

---

app/api/playground.test.ts
app/api/playground.ts

/kind chore
`PlaygroundRpcClient` was missing, added into `/app`.

added missing PlaygroundRpcClient

---

.github/workflows/expo-dependencies.yml

/kind chore
fixed expo upgrade unable to run on dirty tree

fixed expo upgrade unable to run on dirty tree

---

App.tsx
app/__snapshots__/environment.test.ts.snap
app/api/playground.test.ts
app/api/playground.ts
app/environment.ts
app/storage.test.ts
app/wallet/mnemonic.test.ts
hooks/design/useCachedResources.ts

Refactor top level `useCached...` to load Whale after Playground

---

.github/CODEOWNERS
.github/governance.yml
.github/labeler.yml
.github/labels.yml
.github/workflows/oss-governance-project-issue.yml
README.md

/kind chore
Updated `.github/*` health files to reflect recent project structure changes and their associated automation.

updated `.github` health files

---

app/screens/AppNavigator/BottomTabNavigator.tsx
app/screens/WalletNavigator/screens/WalletMnemonicCreate.tsx

/kind fix
Fixed minor ui-ux issues:
- added bottom tab label fixes #249
- not to use primary color labels

fixed minor ui-ux issues

---

.github/dependabot.yml
.github/governance.yml
.github/workflows/oss-governance-labeler.yml

/kind chore
- updated .github/workflows
- updated governance workflow

updated workflow & github health files

---

docker-compose.yml

Bump docker-compose.yml to latest version

---

package-lock.json
package.json

/kind chore
Updates via `expo upgrade`
Fixes #

expo upgrade

---

app/contexts/PlaygroundContext.tsx

/kind fix
Playground is not available in a production environment, it should not be loaded.

PlaygroundContext so it won't be loaded in non-debug mode

---

app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
app/store/ocean.ts

/kind feature
Prevent spending spent utxos
Fixes #
Button will remained disabled until job queue is clear (The "OK" button pressed)

check no pending ocean job

---

app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx

/kind fix
Hide QR code temporarily while screen still in progress
Fixes #

hide QR code while screen not ready yet

---

.github/release-drafter.yml

Removed prerelease from release drafter

---

app/__snapshots__/environment.test.ts.snap
app/environment.ts

temporary disable MainNet for release build

---

BETA_TESTING.md

/kind docs
• Updated documentation
• Add on to Test Results for consistency

Update Beta Testing guide

---

app/__snapshots__/environment.test.ts.snap
app/contexts/PlaygroundContext.tsx
app/contexts/WalletManagementContext.tsx
app/environment.ts
app/screens/Main.web.tsx
package.json

Fixed switching to MainNet

---

.github/CODEOWNERS

Reduce api, contexts and hooks CODEOWNERS to just @fuxingloh

---

.github/governance.yml
.github/labels.yml

design label

---

.github/CODEOWNERS
.idea/dictionaries/fuxing.xml

Mapped remaining CODEOWNERS to @thedoublejay

---

.github/CODEOWNERS

Reduced CODEOWNERS complexity for /app directory

---

BETA_TESTING.md
__mocks__/expo-secure-store.ts
app/__snapshots__/environment.test.ts.snap
app/api/storage/index.test.ts
app/api/storage/provider/provider.native.ts
app/api/wallet/persistence.test.ts
app/environment.ts

/kind fix
Fixes issues on SecureStore for Mobile
Fixes #

fixes from secure store

---

app/screens/AppNavigator/BottomTabNavigator.tsx
app/screens/AppNavigator/screens/Dex/DexScreen.tsx
cypress/integration/functional/dex/poolswap.spec.ts

/kind feature
DEX UI Updates
Fixes #
<div>
</div>

`DEX` - UI Updates

---

app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
cypress/integration/functional/settings.spec.ts

/kind feature
1. Updated UI on Settings Page
2. Changed Exit Wallet to Unlink Wallet
3. Added an Alert before exiting wallet on native
Fixes #358 
https://user-images.githubusercontent.com/25013382/127136470-73b282a1-3728-486a-98be-e91c3acb616e.MP4

`settings` -  UI updates

---

cypress/integration/functional/settings.spec.ts

fixed setting spec

---

app/screens/AppNavigator/AppNavigator.tsx

`#351` - rename duplicated `WalletParamList`

---

app/__snapshots__/environment.test.ts.snap
app/environment.ts

disable testnet as ocean deployment is not available yet

---

cypress/support/commands.ts
cypress/tsconfig.json
package-lock.json
package.json
tsconfig.json

/kind feature
/area e2e
- To improve QoL of e2e testing using Cypress
Fixes #324

Add `@testing-library/cypress/add-commands` for better Cypress Testing QOL

---

app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
app/screens/AppNavigator/screens/Balances/ConvertScreen.tsx
app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexRemoveLiquidity.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
app/screens/AppNavigator/screens/Transactions/TransactionsScreen.tsx
app/screens/AppNavigator/screens/Transactions/screens/TransactionDetailScreen.tsx
app/screens/WalletNavigator/WalletNavigator.tsx
app/screens/WalletNavigator/screens/RestoreWallet/RestoreMnemonicWallet.tsx
cypress/integration/functional/dex/remove_liquidity.spec.ts

/kind fix
UI fixes
1. Use SectionTitle for all pages
2. Sizing issues
3. Color updates
Fixes #

`wallet` - UI fixes

---

app/contexts/WalletContext.tsx

/kind fix
fix crash due to `useNavigation` consumed outside navigation container
Fixes #

remove useNav in context provider, fix crash

---

app/screens/AppNavigator/screens/Settings/SettingsNavigator.tsx
app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/AboutScreen.tsx
cypress/integration/functional/settings.spec.ts

/kind feature
About main page
Fixes #376

`about` - main page

---

.github/workflows/defichain-dependencies.yml

Fixed `defichain-dependencies.yml` jellyfish workflow to only bump jellyfish

---

app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
app/screens/AppNavigator/screens/Balances/ConvertScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.test.tsx
app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

/kind feature
Currently, after a transaction, the state is not updated and balances are not showed properly. This fixes the display to ensure that you have the correct token balances.
Fixes #

update balances on every transaction

---

cypress/integration/functional/dex/available_pool_pairs.spec.ts
docker-compose.yml

Bump docker-compose.yml

---

app/components/CreateWalletStepIndicator.tsx
app/components/OceanInterface/OceanInterface.tsx
app/contexts/DeFiScanContext.tsx
app/screens/WalletNavigator/WalletNavigator.tsx
app/screens/WalletNavigator/screens/CreateWallet/PinConfirmationScreen.tsx
app/screens/WalletNavigator/screens/CreateWallet/PinCreationScreen.tsx
app/screens/WalletNavigator/screens/CreateWallet/VerifyMnemonicWallet.tsx
app/screens/WalletNavigator/screens/RestoreWallet/RestoreMnemonicWallet.tsx
cypress/integration/functional/onboarding/createMnemonicWallet.spec.ts
cypress/integration/functional/onboarding/restore.spec.ts

/kind feature
Ability to set pincode on restore of wallet
Fixes #417

`restore` - pin setup

---

app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.test.tsx
app/screens/TransactionAuthorization.tsx
app/store/wallet.test.ts
app/store/wallet.ts

Fixes some type and langauge.
/kind fix
Fixes #

Typo edits

---

package-lock.json

/kind feature
bump expo deps
Fixes #

bump packages

---

app/components/PinTextInput.tsx

/kind fix
- Autofocus on pin code input
- Center align pin code text
Fixes #449

auto focus on passcode fields

---

app/components/CreateWalletStepIndicator.tsx

/kind fix
- To improve UI during onboarding flow
Fixes #450

`onboarding steppers` - proper case

---

app/components/CreateWalletStepIndicator.tsx

/kind fix
- To fix stepper's description misalignment
Fixes #450

stepper's description misalignment

---

docker-compose.yml

Bump whale:0.8.6 in docker-compose.yml

---

app/__snapshots__/environment.test.ts.snap
app/api/storage/index.test.ts
app/environment.ts

/kind refactor
- Production to default to MainNet
- Enabled TestNet in Preview
- Development to include TestNet and MainNet
Fixes #476

updated `enviroment.ts` `Network` availability

---

app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/PlaygroundNavigator/components/PlaygroundStatus.tsx
app/screens/PlaygroundNavigator/sections/PlaygroundConnection.tsx
app/screens/PlaygroundNavigator/sections/PlaygroundWallet.tsx
app/screens/TransactionAuthorization.tsx
cypress/integration/functional/onboarding/createMnemonicWallet.spec.ts
cypress/integration/smoke/smoke.spec.ts
cypress/support/commands.ts
cypress/support/onboardingCommands.ts
cypress/support/walletCommands.ts
package.json

/kind chore
1. Created `smoke.spec.ts` that runs smoke testing on mainnet. The goal of this test is to run core wallet features that doesn't require balances. (e.g, wallet creation, restore wallet, passphrase etc.)
2. Added some additional tests to verify that connected to MainNet 
3. Added new cypress custom commands, `onboardingCommands` and `walletCommands` for re-usability of tests to be used for Functional and Smoke Testing
4. Persists local storage
5. Tests for #473 #472 #471 #470
Fixes #

`e2e` - expanded tests

---

app/components/HeaderTitle.tsx
app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/AppNavigator/screens/Settings/SettingsNavigator.tsx
app/screens/AppNavigator/screens/Transactions/TransactionsNavigator.tsx
app/screens/PlaygroundNavigator/PlaygroundNavigator.tsx
app/screens/PlaygroundNavigator/sections/PlaygroundConnection.tsx
app/screens/WalletNavigator/WalletNavigator.tsx
app/store/block.test.ts
app/store/block.ts
cypress/integration/functional/wallet/balances/receive.spec.ts
cypress/integration/functional/wallet/dex/available_pool_pairs.spec.ts
cypress/integration/smoke/smoke.spec.ts
cypress/support/walletCommands.ts

/kind feature
1. APR for DEX
2. Network name and Connected state (Red or Green) on header title
Fixes #423 #466

`DEX` - APR and `Header` - Network with Connected state

---

eas.json
metro.config.js
package-lock.json
package.json

Updated eas.json

---

package-lock.json
package.json

Added eas-cli into devDeps; so it can be tracked by dependabot

---

app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx

/kind fix
- To improve UI in Add Liquidity screen
Fixes #469
Not tested on Android

`liquidity` - right-align price 

---

app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
app/screens/AppNavigator/screens/Balances/ConvertScreen.tsx
app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
app/screens/AppNavigator/screens/Settings/screens/CommunityScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/__snapshots__/CommunityScreen.test.tsx.snap

/kind feature
1. Hide back titles
2. add defiscan link
Fixes #

ui fixes, add defiscan link

---

app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
app/screens/AppNavigator/screens/Transactions/screens/TransactionDetailScreen.tsx

/kind fix
- To improve long text visibility in Transaction Detail Screen and Estimated to Receive in Pool Swap Screen
- Tested on both iOS and Android

Overflow Estimated to Receive and Txid

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-enhancement.md
.github/ISSUE_TEMPLATE/3-general.md
.github/ISSUE_TEMPLATE/4-ui-ux-improvements.md
.github/ISSUE_TEMPLATE/5-translation-improvements.md
.github/workflows/expo-preview.yml
BETA_TESTING.md
CONTRIBUTING.md
LICENSE
README.md
app.json
app/screens/WalletNavigator/screens/CreateWallet/EnrollBiometric.tsx
app/store/index.ts
app/translations/index.ts

Update app name to `DeFiChain Wallet`

---

App.tsx
app/components/HeaderTitle.tsx
app/contexts/StatsContext.tsx
app/hooks/wallet/PoolPairsAPI.ts
app/hooks/wallet/TokensAPI.ts
app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
app/screens/AppNavigator/screens/Transactions/TransactionsScreen.tsx
app/screens/AppNavigator/screens/Transactions/screens/TransactionDetailScreen.tsx
app/store/wallet.test.ts
app/store/wallet.ts
cypress/integration/functional/wallet/balances/balances.spec.ts
cypress/integration/functional/wallet/balances/convert/convert.spec.ts
cypress/integration/functional/wallet/balances/convert/convert_account_to_utxos.spec.ts
cypress/integration/functional/wallet/balances/convert/convert_utxos_to_account.spec.ts
cypress/integration/functional/wallet/balances/receive.spec.ts
cypress/integration/functional/wallet/balances/send.spec.ts
cypress/integration/functional/wallet/balances/tokenDetail.spec.ts
cypress/integration/functional/wallet/dex/add_liquidity.spec.ts
cypress/integration/functional/wallet/dex/confirm_add_liq.spec.ts
cypress/integration/functional/wallet/dex/remove_liquidity.spec.ts
cypress/integration/functional/wallet/transaction/detail.spec.ts
cypress/integration/smoke/smoke.spec.ts

/kind feature
1. Add refresh of balance and poolpairs based on block update
2. Moved Stats interval to `StatsContext`
3. Removed fetchBalances on e2e tests since balances are updated per block
Fixes #492

add polling based on blocks

---

app/api/wallet/passcode_attempt.ts
app/components/OceanInterface/OceanInterface.tsx
app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
app/screens/TransactionAuthorization.tsx
app/store/authentication.ts
cypress/integration/functional/wallet/authorization/transactionAuthorization.spec.ts

/kind fix
1. Fix issues with Transaction UI
2. Fixes #513 - It happens because there's an error on the initial transaction and not on the signing itself. Causing it to auto-retry even without any inputs
3. Fixes #475 - Attempt is recovered from LocalStorage
4. Fixes #462 - Cancelling should work now and not re-trigger
5. Added e2e tests to cover all these scenarios
Fixes #

`transaction ui` - fixes

---

app/screens/AppNavigator/screens/Balances/screens/ReceiveScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/__snapshots__/ReceiveScreen.test.tsx.snap
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

/kind fix
Text align on mobile
Fixes #

`copy` - alignment fix

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/6-e2e-improvements.md
.github/labels.yml
.github/workflows/ci.yml
.github/workflows/drift.yml
.github/workflows/expo-preview.yml
.idea/dictionaries/fuxing.xml

/kind chore
1. Added KY as Cypress code owner
2. E2E Type for request
3. Bug label categorization
Fixes #

workflow updates

---

app/components/PinTextInput.tsx

/kind fix
1. Update design
2. Fixes alignment due to change of design
3. Added autofocus on Android
Fixes #538 
Fixes #449

pin input updates

---

app/screens/TransactionAuthorization.tsx

/kind fix
cyclic hook dep causing passcode prompting fail state check
Fixes #522 
Fixes #541

Fix unable to sign tx

---

app/components/OceanInterface/OceanInterface.tsx
app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/ConfirmPoolSwapScreen.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
cypress/integration/functional/wallet/dex/poolswap.spec.ts

/kind feature
1. Pool swap confirm page
Fixes #552

`pool swap` - confirm page

---

App.tsx
app/contexts/StoreProvider.tsx
app/screens/PlaygroundNavigator/PlaygroundNavigator.tsx

/kind refactor
Refactor `<PlaygroundProvider/>` not be part of `<Main/>` hierarchy.
Also renamed `WalletStoreProvider` to `StoreProvider`.

refactor `<PlaygroundProvider/>` not be part of `<Main/>` hierarchy

---

app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

/kind fix
1. When swapping tokens, pool swap price remains
Fixes #578

fix for swap price

---

app/components/HeaderTitle.tsx

Added `<HeaderTitle>` padding on iOS as it's hugging too close to border

---

app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
app/screens/AppNavigator/screens/Balances/__snapshots__/BalancesScreen.test.tsx.snap
app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexConfirmAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
cypress/integration/functional/wallet/dex/confirm_add_liq.spec.ts
cypress/integration/functional/wallet/dex/remove_liquidity.spec.ts
cypress/integration/smoke/smoke.spec.ts

/kind fix
Update to 8 decimal places due to not displayed on small amounts
Fixes #

decimal changes and ui fixes

---

docker-compose.yml

/kind fix
This will prevent certain `503` errors on the playground when testing.

add -rpcworkqueue=512 to docker-compose.yml

---

app/components/ConfirmComponents/index.tsx
app/screens/AppNavigator/screens/Balances/screens/ConvertConfirmationScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendConfirmationScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/__snapshots__/TokenDetailScreen.test.tsx.snap
app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/ConfirmPoolSwapScreen.tsx
cypress/integration/functional/wallet/balances/convert/convert.spec.ts
cypress/integration/functional/wallet/balances/send.spec.ts
cypress/integration/functional/wallet/dex/poolswap.spec.ts

/kind refactor
1. Refactor common components for Confirm Page
2. Mostly views with same layouts
Fixes #

refactor common components for confirm page

---

.github/workflows/ci-e2e.yml

/kind chore
- removed on merge: [ main ] and instead to run on cron daily
- added tag for possible Slack triggering for #489

`ci-e2e.yml`: removed on merge: [ main ] and instead to run on cron daily

---

docker-compose.yml

Bump `playground:0.8.6` & `whale:0.8.9` in docker-compose.yml

---

app/screens/AppNavigator/screens/Dex/DexScreen.tsx

/kind feature
Display pooled tokens 
Fixes #529

`dex` - display individual pooled

---

app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/ReceiveScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/__snapshots__/ReceiveScreen.test.tsx.snap
app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
app/screens/AppNavigator/screens/Transactions/TransactionsNavigator.tsx
app/screens/WalletNavigator/screens/CreateWallet/VerifyMnemonicWallet.tsx
app/screens/WalletNavigator/screens/RestoreWallet/RestoreMnemonicWallet.tsx
app/store/wallet.ts

/kind fix
1. Add <LoadingScreen> while components are not ready is causing some flicker on screen momentarily. It's smoother now without it.
2. Duplicate route names. Warning is thrown on navigation
3. Make receive page selectable
4. Update DeFi Token Name
Fixes #583

prevent flicker on load of page, receive address selectable, route names update

---

__mocks__/expo-random.ts
app/api/wallet/provider/mnemonic_unprotected.test.ts
app/api/wallet/provider/mnemonic_unprotected.ts
app/screens/PlaygroundNavigator/sections/PlaygroundWallet.tsx
app/screens/WalletNavigator/screens/CreateWallet/CreateMnemonicWallet.tsx

/kind refactor
This PR centralizes the mnemonic generation process into one method for consistency to prevent insecure entropy misuse.

refactor mnemonic generation into `MnemonicUnprotected.generateWords`

---

cypress/support/commands.ts
package-lock.json
package.json

Bump @defichain/playground dependencies from 0.8.5 to 0.8.6

---

app/screens/AppNavigator/screens/Dex/DexConfirmRemoveLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
app/screens/AppNavigator/screens/Dex/DexRemoveLiquidity.tsx
cypress/integration/functional/wallet/dex/remove_liquidity.spec.ts

/kind feature
Fixes https://github.com/DeFiCh/wallet/issues/563

`remove liquidity` - confirm page

---

app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
app/screens/AppNavigator/screens/Settings/components/RowNetworkItem.tsx

/kind feature
1. Show warning alert when switching networks to prevent accidental exit of wallet
Fixes #604

network switch warning

---

app/screens/AppNavigator/screens/Balances/screens/ConvertConfirmationScreen.tsx
app/screens/AppNavigator/screens/Dex/DexConfirmAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/ConfirmPoolSwapScreen.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

/kind fix
1. Share of Pool consistency
2. DEX title update
Fixes #

`Add Liquidity` - Share of Pool display, `DEX` Title update

---

app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/ChangePinScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/ConfirmPinScreen.tsx
app/screens/TransactionAuthorization.tsx
app/store/authentication.ts

/kind feature
Added loading message option into option (pushed to store)
bug fix - not using message pushed from caller
Fixes #496 
Fixes #560

Customizable `TransactionAuthorization` labels

---

app/screens/AppNavigator/screens/Settings/screens/ConfirmPinScreen.tsx
app/screens/WalletNavigator/screens/CreateWallet/PinConfirmation.tsx

/kind feature
- To inform user of potential long waiting time during wallet encryption during pin creation flow
Fixes #495
Tested on iPhone 12 and pixel 3a emulator

Add copy "encrypting wallet this may take 20 seconds

---

app/screens/AppNavigator/screens/Balances/screens/ConvertConfirmationScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendConfirmationScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
app/screens/AppNavigator/screens/Dex/DexConfirmAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexConfirmRemoveLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexRemoveLiquidity.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/ConfirmPoolSwapScreen.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

wait for all tx signed and broadcasted

---

cypress/integration/functional/wallet/authorization/transactionAuthorization.spec.ts
cypress/plugins/index.ts

/kind chore
Double entry, causing code coverage generation to be missing.

fixed cypress plugin/index.ts

---

app/screens/AppNavigator/screens/Settings/screens/AboutScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/CommunityScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/__snapshots__/AboutScreen.test.tsx.snap
app/screens/AppNavigator/screens/Settings/screens/__snapshots__/CommunityScreen.test.tsx.snap
cypress/integration/functional/wallet/settings/community.spec.ts

/kind feature
- To inform user of our official social links and telegram announcement channel
Fixes #643
Tested on iPhone 12 and pixel 3a emulator

add social media links on about page

---

.github/CODEOWNERS

adding @kyleleow to codeowners

---

app/screens/AppNavigator/screens/Settings/SettingsNavigator.tsx
app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
app/screens/AppNavigator/screens/Settings/components/RowNetworkItem.tsx
app/screens/AppNavigator/screens/Settings/screens/NetworkSelectionScreen.test.tsx
app/screens/AppNavigator/screens/Settings/screens/NetworkSelectionScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/__snapshots__/NetworkSelectionScreen.test.tsx.snap
cypress/integration/functional/wallet/settings/settings.spec.ts
cypress/integration/smoke/smoke.spec.ts
cypress/support/commands.ts

/kind feature
- To discourage user from switching network
Fixes #652
Tested on iPhone 12 and pixel 3a emulator

`network` - update selection screen

---

app/screens/WalletNavigator/screens/components/OnboardingCarousel.tsx

/kind feature
Fixes #344 
<div>
</div>

updated welcome page

---

app/screens/AppNavigator/screens/Balances/screens/SendConfirmationScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
cypress/integration/functional/wallet/balances/send.spec.ts

use different DfTx when max DFI sent

---

App.tsx
app/screens/ConnectionBoundary/ConnectionBoundary.test.tsx
app/screens/ConnectionBoundary/ConnectionBoundary.tsx
app/screens/ConnectionBoundary/__snapshots__/ConnectionBoundary.test.tsx.snap
app/screens/WalletNavigator/screens/CreateWallet/CreateMnemonicWallet.tsx

/kind fix
- Dark Mode for Connection Boundary
- Move down to context
Fixes #

dark mode for offline mode and fix for translations

---

app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
app/translations/languages/de.json

/kind chore
• German translation 
Add on to #710

• Add German (de) translation for Wallet

---

app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/AppNavigator/screens/Transactions/TransactionsScreen.tsx
app/screens/AppNavigator/screens/Transactions/screens/TransactionDetailScreen.tsx

/kind feature
- For code consistencies
Fixes #694
Tested on iPhone 12 and pixel 3a emulator

render function component instead of calling it

---

.idea/codeStyles/Project.xml

applied code style to match eslint

---

.github/PULL_REQUEST_TEMPLATE.md

/kind docs
Added some developer checklist to make sure everything is checked before submitting a PR for review
Fixes #

developer checklist

---

app/components/SkeletonLoader.tsx
app/components/skeletonLoaders/DexSkeletonLoader.tsx
app/components/skeletonLoaders/MnemonicWordSkeletonLoader.tsx
app/components/skeletonLoaders/SkeletonLoader.test.tsx
app/components/skeletonLoaders/TransactionSkeletonLoader.tsx
app/components/skeletonLoaders/__snapshots__/SkeletonLoader.test.tsx.snap
app/screens/WalletNavigator/screens/RestoreWallet/RestoreMnemonicWallet.tsx
cypress/integration/functional/wallet/settings/settings.spec.ts

On restore wallet page, there's a brief loading time before displaying the page. In this PR the skeleton loader is added to have a smoother transition.
/kind feature
Fixes #733

Added mnemonic skeleton loader for restore wallet screen

---

.github/PULL_REQUEST_TEMPLATE.md

/kind chore
Moved developer checklist down so that important descriptions appear above. (This section)
This makes PR preview on messaging channels much more readable and concise.

moved developer checklist down so that important description appear above

---

app/screens/AppNavigator/screens/Balances/screens/ConvertConfirmationScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendConfirmationScreen.tsx
app/screens/AppNavigator/screens/Dex/DexConfirmAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/DexConfirmRemoveLiquidity.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/ConfirmPoolSwapScreen.tsx
app/translations/languages/de.json

/kind feature
German translations for preview message in Transaction Authorization prompt. Example, Converting 1 UTXO to Token for following screen
- Convert
- Send
- Add LP
- Remove LP
- Swap
Fixes #750

Added German translation for confirm screen preview message

---

docker-compose.yml

updated `ghcr.io/defich/whale:0.9.2`

---

app/translations/languages/de.json

/kind chore
• Update & edit German translation
Fixes #

• Edited German (de) translation for Wallet

---

app/screens/AppNavigator/screens/Balances/screens/TokensVsUtxoScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/__snapshots__/TokensVsUtxoScreen.test.tsx.snap

/kind fix
- To improve on text readability
Fixes #739

`UI` - fix text overflow in UTXO vs Token screen

---

app/translations/languages/de.json

/kind chore
• Update & edit German translation
Fixes #766

Edited German (de) translation for Wallet

---

cypress/integration/functional/wallet/dex/add_liquidity.spec.ts

/kind feature
Combine Add and Confirm Liquidity Spec.
Submit button must be disabled on these scenarios
- Zero values
- NaN inputs
- More than input Token A
-  More than input Token B
- Clicking on Max for Token A, while Token B doesn't have enough balance
- Clicking on Max for Token B, while Token B doesn't have enough balanc
- Clicking on Continue must redirect to confirm page. Check URL if correct
Fixes #388

E2E for add liquidity and confirm liquidity spec

---

app/api/wallet/mnemonic_storage.test.ts
app/api/wallet/mnemonic_storage.ts
app/api/wallet/persistence.test.ts
app/api/wallet/provider/mnemonic_encrypted.test.ts
app/api/wallet/provider/mnemonic_unprotected.test.ts

/kind feature
- Improve code coverage on `app/api/wallet`
Fixes #716

`jest` - add test coverage for `app/api/wallet`

---

app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
app/screens/AppNavigator/screens/Balances/__snapshots__/BalancesScreen.test.tsx.snap
app/translations/languages/de.json

updated translations

---

app/screens/ConnectionBoundary/ConnectionBoundary.tsx
app/screens/ConnectionBoundary/__snapshots__/ConnectionBoundary.test.tsx.snap
app/translations/languages/de.json

Offline mode - updated screen

---

app/components/InfoText.test.tsx
app/components/InfoText.tsx
app/components/__snapshots__/InfoText.test.tsx.snap
app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
app/styles.json
app/tailwind.config.js
app/translations/languages/de.json
cypress/integration/functional/wallet/balances/send.spec.ts

/kind feature
- To prevent users from being confused on why their balance reflected is different
Fixes #759

`send` - add info to inform reserved UTXO

---

.github/workflows/ci-e2e.yml

increased Cypress parallelization to 8 for faster CI

---

app/screens/AppNavigator/BottomTabNavigator.tsx

update dex icon

---

app/screens/WalletNavigator/screens/CreateWallet/VerifyMnemonicWallet.tsx

Fix: #804
/kind fix
- To allow the user to see all the options if they could not fit their device's width
Fixes #804

`verify wallet` - fix word option overflowing

---

app/components/InfoText.tsx
app/components/__snapshots__/InfoText.test.tsx.snap
app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
app/screens/AppNavigator/screens/Settings/components/RowLanguageItem.tsx
app/screens/AppNavigator/screens/Settings/screens/__snapshots__/LanguageSelectionScreen.test.tsx.snap
app/translations/languages/de.json
cypress/integration/functional/wallet/balances/convert/convert.spec.ts

/kind feature
- To prevent users from being confused on why their balance reflected is different
Fixes #736

`convert` - add info text to inform reserved UTXO

---

app/screens/Main.tsx
app/screens/TransactionAuthorization.tsx

fixed overlapping status bar

---

app/screens/TransactionAuthorization.tsx
cypress/integration/functional/wallet/authorization/transactionAuthorization.spec.ts

`transaction authorization` - reduce to 3 attempts

---

app/components/icons/assets/_Default.tsx
app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendConfirmationScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
app/store/wallet.test.ts
app/store/wallet.ts

/kind chore
Updated default Icon to use first alphabet in capital case
Fixes #825

Updated default Icon to use first alphabet in capital case

---

app/screens/WalletNavigator/screens/CreateWallet/CreateMnemonicWallet.tsx

Disabled the verify button on refresh recovery word

---

app/translations/languages/de.json
package-lock.json
package.json

/kind chore
Fixes #
https://github.com/expo/eas-cli/issues/607

added react-reanimated lib to fix build

---

app/translations/languages/de.json

/kind chore
• Typographical error in German translation
Fixes #

`Translation` - Edited German (de)

---

app/translations/languages/de.json

/kind chore
• Updated german translation
Fixes #

`Translation` - German (de) translation 

---

app/screens/AppNavigator/screens/Settings/components/RowLanguageItem.tsx
cypress/integration/functional/wallet/settings/settings.spec.ts

/kind fix
Display translated language instead of display name
Fixes #

update language title

---

mobile-app/app/translations/languages/de.json

/kind fix
Fixes #924
Changed German translation on page create wallet guidelines

Changed german translation on page create wallet guidelines

---

mobile-app/app/screens/AppNavigator/screens/Settings/SettingsNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/AboutScreen.test.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/AboutScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/CommunityScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/AboutScreen.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/CommunityScreen.test.tsx.snap
mobile-app/app/translations/languages/de.json
mobile-app/app/translations/languages/zh-Hans.json
mobile-app/app/translations/languages/zh-Hant.json
mobile-app/cypress/integration/functional/wallet/settings/community.spec.ts

/kind feature
1. Updated about screen (Gradient not added due to low support)
2. Removed community link from header
Fixes #813

`about` - updated design

---

mobile-app/app/components/WalletTextInput.tsx
mobile-app/app/components/__snapshots__/WalletTextInput.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx
mobile-app/app/translations/languages/de.json
mobile-app/app/translations/languages/zh-Hans.json
mobile-app/app/translations/languages/zh-Hant.json
mobile-app/cypress/integration/functional/wallet/dex/poolswap.spec.ts

/kind feature
- To update the input field UI to match latest prototype in v0.10.0
Fixes #929

`pool swap` - update input field's UI

---

mobile-app/app/components/IconButton.tsx
mobile-app/app/components/__snapshots__/IconButton.test.tsx.snap
mobile-app/app/components/icons/assets/BTC.tsx
mobile-app/app/components/icons/assets/DFI.tsx
mobile-app/app/components/icons/assets/__snapshots__/index.test.tsx.snap
mobile-app/app/components/icons/assets/dBCH.tsx
mobile-app/app/components/icons/assets/dBTC.tsx
mobile-app/app/components/icons/assets/dDFI.tsx
mobile-app/app/components/icons/assets/dDOGE.tsx
mobile-app/app/components/icons/assets/dETH.tsx
mobile-app/app/components/icons/assets/dLTC.tsx
mobile-app/app/components/icons/assets/dUSDC.tsx
mobile-app/app/components/icons/assets/dUSDT.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/__snapshots__/TokensVsUtxoScreen.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx
mobile-app/app/translations/languages/de.json
mobile-app/app/translations/languages/zh-Hans.json
mobile-app/app/translations/languages/zh-Hant.json
mobile-app/cypress/integration/functional/wallet/dex/add_liquidity.spec.ts
mobile-app/cypress/integration/functional/wallet/dex/available_pool_pairs.spec.ts
mobile-app/cypress/integration/functional/wallet/dex/poolswap.spec.ts
mobile-app/cypress/integration/functional/wallet/dex/remove_liquidity.spec.ts
mobile-app/cypress/integration/smoke/smoke.spec.ts

/kind feature
- To update dex screen's UI to match v0.11.0
Fixes #928

`DEX` - update UI

---

mobile-app/app/contexts/LocalAuthContext.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
mobile-app/app/translations/languages/de.json
mobile-app/app/translations/languages/zh-Hans.json
mobile-app/app/translations/languages/zh-Hant.json

/kind feature
- To clarify authentication methods
Fixes #911 
- Requires testing on other devices that use different authentication methods

`privacy lock` - update label

---

mobile-app/app/translations/languages/de.json

/kind feature
- To add german translations to privacy lock label
Fixes #

translation: update german entries

---

mobile-app/app/translations/languages/de.json

/kind
- To update german translation for "iris scan"
Fixes #

translation: fine tune 'iris scan'

---

index.js
mobile-app/index.js
package.json

/kind chore
Fix failing builds
Fixes #

moved index.js

---

.github/CODEOWNERS

added @fullstackninja864 as code owner

---

mobile-app/app/contexts/LocalAuthContext.tsx
mobile-app/app/translations/languages/de.json
mobile-app/app/translations/languages/zh-Hans.json
mobile-app/app/translations/languages/zh-Hant.json

/kind fix
- To use the same label for all biometric authentication types for Android devices
Fixes #965

`privacy lock` - fix biometric lock label on android

---

mobile-app/app/screens/PrivacyLock.tsx

/kind fix
- To check if `privacyLock.isEnabled` is blocking authentication prompt
Fixes #977

`privacy lock` - POC to test prompting on fresh start

---

mobile-app/app/contexts/DeFiScanContext.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.test.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/__snapshots__/TokenDetailScreen.test.tsx.snap
mobile-app/cypress/integration/functional/wallet/balances/tokenDetail.spec.ts

/kind feature
When viewing token details, we should be able to redirect to DeFiScan to show details of token. Example, Balances -> dBTC -> View Token Details -> DeFiScan Token Detail
Fixes #947

Token info redirection to defiscan token detail screen

---

.github/CODEOWNERS

added missing codeowner for /.github/

---

docker-compose.yml
mobile-app/app/api/wallet/index.test.ts
mobile-app/app/contexts/WhaleContext.tsx
mobile-app/cypress/integration/functional/wallet/balances/send.spec.ts
package-lock.json

Bump @defichain/playground dependencies

---

.github/dependabot.yml

set dependabot update schedule to daily from weekly to further shift left deps update timeline

---

app.json

/kind chore
Added missing intent filters for Android 11 for expo-linking - https://docs.expo.dev/guides/linking/#deep-links-on-android
Fixes #

add missing intent filters for Android 11

---

mobile-app/app/components/OceanInterface/OceanInterface.tsx

/kind fix
Missing color for error button in Ocean Interface
Fixes #

missing colors

---

mobile-app/app/store/wallet.ts
mobile-app/cypress/integration/smoke/smoke.spec.ts

Updated dat DFI token display name.

---

mobile-app/app/components/WalletTextInput.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexRemoveLiquidity.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

/kind fix
- To fix set amount button and clear input button from overflowing the input field container when there are input
- To fix clear input button custom background layer from misaligning when there height of input field changes
Fixes #991

`input field` - fix button overflow

---

.github/workflows/eas-build.yml

updated eas-build.yml to trigger instead on enqueue so that it doesn't linger on orange status icon

---

mobile-app/app/translations/languages/de.json

/kind chore
• Current word "Licenses" in German breaks UI
Fixes #

`Translation` - Edited German (de) translation in About screen

---

mobile-app/app/components/SkeletonLoader.tsx
mobile-app/app/components/skeletonLoaders/LoanSkeletonLoader.tsx
mobile-app/app/components/skeletonLoaders/SkeletonLoader.test.tsx
mobile-app/app/components/skeletonLoaders/VaultSkeletonLoader.tsx
mobile-app/app/components/skeletonLoaders/__snapshots__/SkeletonLoader.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmCreateVaultScreen.tsx

/kind feature
- This is to create a static loader for loans while it's loading the data
Fixes #1200

Create loans skeleton loader

---

mobile-app/cypress/tsconfig.json

/kind chore
To hide pesky IDE errors.

added moduleResolution: node for cypress tests so that IDE doesn't show an error

---

mobile-app/app/api/releaseChannel.ts
mobile-app/app/api/secured/index.ts
mobile-app/app/components/OceanInterface/OceanInterface.tsx
mobile-app/app/contexts/FeatureFlagContext.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/NetworkSelectionScreen.tsx
mobile-app/app/screens/PrivacyLock.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/OnboardingNetworkSelectScreen.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/VerifyMnemonicWallet.tsx

This reverts commit 92023f160049eab8f9db425aed61eb724d0e7476.
/kind chore
Updated release channel to work with Desktop. Currently, releaseChannel is only updated on EAS-cli which we don't use for Desktop builds. Reference - https://github.com/expo/expo-cli/issues/948
Fixes #

update release channel

---

shared/translations/languages/de.json

/kind chore
• Update German translation, typos
Fixes #

Update Translation (de)

---

shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

translations update

---

docker-compose.yml
package.json

https://github.com/DeFiCh/playground/pull/261

Bump playground from 0.11.2 to 0.11.3

---

mobile-app/app/components/LoanCards.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts
mobile-app/cypress/tsconfig.json

/kind feature
Add loan prices for each loan
Fixes #

added loan prices

---

website/src/pages/api/v0/announcements.ts

`loans` - announcements

---

mobile-app/app/contexts/FeatureFlagContext.tsx
mobile-app/app/contexts/__mocks__/FeatureFlagContext.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/AboutScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/AboutScreen.test.tsx.snap
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts
mobile-app/cypress/integration/functional/wallet/settings/featureGate.spec.ts
website/src/pages/api/v0/settings/flags.ts

`website` - bump loans to Beta

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/FeatureFlagScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/FeatureFlagScreen.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

`feature flags` - label update

---

mobile-app/app/components/BottomSheetTokenList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/Vaults.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmEditCollateralScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/EditCollateralScreen.tsx
shared/store/loans.ts
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
1. Wait for initial fetch of data to prevent empty vault flicker
2. Renamed AddCollateralScreens to EditCollateral
3. Prefetch Loan schemes
4. Changed View to ScrollView for Vaults screen
Fixes #

`loans` - ui clean up

---

mobile-app/app/components/Tabs.test.tsx
mobile-app/app/components/__snapshots__/Tabs.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/EmptyLoan.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/LoansTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailTabSection.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCards.test.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCards.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/Vaults.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ChooseLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/CreateVaultScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json
website/src/pages/api/v0/settings/flags.ts

/kind feature
1. Translations
2. Loans empty state
3. Vault card - Manage loans
Fixes #1332

`loans` - ui updates

---

mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/Vaults.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/CreateVaultScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/EditCollateralScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/LoansFaq.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/LoansFaq.test.tsx.snap
shared/translations/languages/de.json
website/src/pages/api/v0/settings/flags.ts

/kind chore
Added de translations and ui fixes
Fixes #

`loan` - translations and minor ui updates

---

mobile-app/app/components/TokenIconGroup.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/CollateralsTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/DetailsTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/LoansTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetVaultList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatioDisplay.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultStatusTag.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultInfo.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/hooks/CollateralizationRatio.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/EditCollateralScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/LoansFaq.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/LoansFaq.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

By adjusting max ratio based on at risk threshold
Fixes: #1377
/kind feature
Fixes #1377

`col ratio health bar` - change max ratio to display more healthy region

---

mobile-app/app/components/BottomSheetTokenList.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/PricesSection.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatio.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmEditCollateralScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Transactions/EmptyTransaction.tsx
mobile-app/app/screens/AppNavigator/screens/Transactions/__snapshots__/EmptyTransaction.test.tsx.snap
mobile-app/cypress/integration/functional/wallet/transaction/list.spec.ts
mobile-app/cypress/integration/functional/wallet/transaction/list_empty.spec.ts
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

`composite swap` - number format and empty state

---

mobile-app/app/components/HeaderSearchIcon.tsx
mobile-app/app/components/HeaderSearchInput.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ChooseLoanTokenScreen.tsx

`browser loan` - add search UI to header

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx

show 8 decimal places for outstanding amount in payback loan screen

---

website/src/pages/api/v0/announcements.ts

updated announcements

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx

Remove color for min collateral value

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanSchemeOptions.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultStatusTag.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap

Loan scheme UI changes for scheme listing and  risk status bg color

---

mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/CloseVaultScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmCreateVaultScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmEditLoanSchemeScreen.tsx

/kind feature
- To allow user to close vault
Fixes #1383

`close vault` - add UI and integrate API

---

mobile-app/app/api/transaction/dfi_converter.ts
mobile-app/app/components/index.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/FeatureFlagScreen.test.tsx.snap
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/CreateWalletGuidelines.test.tsx.snap
shared/translations/languages/de.json

/kind fix
1. Converting label fix
2. Sort (FROM) tokens in Composite swap to move up token with balances
Fixes #1448

`loans and composite swap` - ui fixes

---

shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Translation update

---

mobile-app/app/components/TokenIconGroup.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultInfo.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

`translation` - add entries for close vault

---

shared/translations/languages/de.json

/kind chore
• Some typos on app spotted
Fixes #

Translation (DE): typo

---

mobile-app/app/components/NumberRow.tsx
mobile-app/app/components/__snapshots__/ConversionDetailsRow.test.tsx.snap
mobile-app/app/components/__snapshots__/TransactionResultsRow.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/PricesSection.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/NetworkDetails.test.tsx.snap

/kind fix
- The alignment to the right isn't working because the suffix is taking up space on both lines. Utilized `Text` as children to properly align
Fixes #

Fix UI alignment on Prices Section on word break

---

mobile-app/app/components/SkeletonLoader.tsx
mobile-app/app/components/skeletonLoaders/VaultSkeletonLoader.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailTabSection.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmBorrowLoanTokenScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
- Various UI bugfixes for loan-related screens
Fixes #1425
Fixes #1444 
Fixes #1453 
Fixes #1441

`loan UI` - fix various issues

---

website/src/pages/api/v0/announcements.ts
website/src/pages/api/v0/settings/flags.ts

/kind chore
Enable loans on MainNet
Fixes #

enable loans

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/CreateVaultScreen.tsx
shared/translations/languages/de.json

update conversion to 2.1 DFI for vault fees

---

mobile-app/app/screens/AppNavigator/screens/Dex/helpers/path-finding.tsx

Fix composite swap

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionTimeProgress.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BidCard.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BrowseAuctions.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/hooks/AuctionTimeLeft.ts
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/CollateralsTab.tsx
shared/store/auctions.ts
shared/store/loans.ts
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
- To display data from API
- Add custom price for DUSD for auctions
- Add logic to display the progress bar of auction time left
- Update UI of collateral tab in vault details during liquidated state
- Partially fixed #1471  since we are still missing bid history API for `manage bid` screen
Fixes #

`browse auctions` - integrate API 

---

shared/translations/languages/de.json

/kind chore
• Translation consistency updates
Fixes #

Translation (DE): amendments

---

mobile-app/app/components/BarCodeScanner.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
mobile-app/cypress/integration/functional/wallet/balances/send.spec.ts
package-lock.json
package.json

`qr scanner` - fix expo 43 regression on `expo-barcode-scanner`

---

mobile-app/app/hooks/wallet/TokensAPI.ts

token display fix

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.test.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx

Highest bid flag in auction listing to show user who placed highest bid

---

shared/store/auctions.ts
shared/store/loans.ts

/kind feature
Increase fetch size to 200 to ensure it will be displayed:
- Vaults
- Loan Tokens
- Auctions
Fixes #1531

Increase fetch size (200) for vaults, auctions and loan tokens

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/BrowseAuctions.tsx
website/src/pages/api/v0/settings/flags.ts

`auctions` - sort 

---

mobile-app/app/screens/AppNavigator/screens/Auctions/AuctionDetailScreen.tsx

Auction Details tab - Additional details are covered by the submit buttons, cannot view it on iPhone SE 

---

mobile-app/app/screens/AppNavigator/screens/Auctions/AuctionDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionDetails.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionedCollaterals.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/CollateralTokenItemRow.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/QuickBid.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/helpers/ActivePrice.ts
mobile-app/app/screens/AppNavigator/screens/Auctions/hooks/AuctionBidValue.ts
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/ConfirmPlaceBidScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/PlaceBidScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/LoansFaq.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/__snapshots__/LoansFaq.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Update Vault and auction Translation

---

mobile-app/app/screens/AppNavigator/screens/Auctions/AuctionDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionDetails.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.test.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/BatchCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/hooks/AuctionBidValue.ts
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/PlaceBidScreen.tsx

/kind fix
Fix total auction value in the ff screens
- Auction Cards
- Auction Detail Screen
- Place Bid Screen
Fixes #1545

Fix all calculation for total auction value

---

mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmEditCollateralScreen.tsx
shared/store/auctions.ts

/kind feature
1. Adds a notif on bottom nav
2. Fixes vault share display
Fixes #1547 
Fixes #1546

`loans and auctions` - auctions count, vault share fix

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionTimeProgress.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/BatchCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/BidCard.test.tsx.snap

`auction progress bar` - revert UI to countdown

---

mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmBorrowLoanTokenScreen.tsx

/kind feature
- To not perform DFI conversion when borrow loan
Fixes #1544

`borrow loan` - remove dfi conversion check

---

mobile-app/app/screens/AppNavigator/screens/Auctions/AuctionDetailScreen.tsx

/kind fix
- The batch index from api should be used
Fixes #1557

Use index from batch api

---

mobile-app/app/screens/AppNavigator/screens/Balances/screens/SendConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

`translation` - add entries to sending LP tokens

---

mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx

Fix wrong swap with token name displayed in token details screen 

---

mobile-app/app/screens/AppNavigator/screens/Auctions/AuctionDetailScreen.tsx
shared/contexts/DeFiScanContext.tsx

Redirect auction batch to defiscan auction batch url #1590

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/QuickBid.tsx

translations issue

---

website/src/pages/api/v0/announcements.ts

Emergency announcement

---

mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/LoansTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/hooks/LoanOperations.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/EditCollateralScreen.tsx

/kind fix
Allow adding of collateral and payback of loans even if vault is halted
Fixes #1609

`loans` - allow to add col and payback loan on halted state

---

mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx

/kind fix
Removed auctions notif in the meantime due to performance issues
Fixes #

`auctions` - removed auctions notif

---

package-lock.json
package.json

reanimated rollback

---

website/src/pages/api/v0/announcements.ts

emergency announcements

---

website/src/pages/api/v0/announcements.ts

`emergency` - de translations

---

website/src/pages/api/v0/announcements.ts

zh translations

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowMoreScreen.tsx

/kind feature
- This allows the user see the loan amount in USD
Fixes #1596
- Will add translations with other missing ones in another PR

Borrow Loan Token - display USD value 

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexConfirmAddLiquidity.tsx

/kind fix
Fix price display on add liquidity and confirm liquidity 
Fixes #1625

`DEX` - add liquidity price display fix

---

mobile-app/app/components/InputHelperText.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowMoreScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx

/kind feature
- Display the USD value on the ff screens
- Borrow more
- Payback loan
- Fix display of `NaN` in Borrow Loan screen when input is not a number
Fixes #1597

Display USD value in payback and borrow more

---

shared/translations/languages/de.json

/kind chore
• Amendment of typo
Fixes #

Translation (DE): amend typo

---

mobile-app/app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/AddressControlScreen.test.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/AddressControlScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/__snapshots__/AddressControlScreen.test.tsx.snap
shared/contexts/WalletContext.tsx
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Discover addresses from address listing page

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/EditCollateralScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

translations fixes

---

mobile-app/app/components/Tabs.tsx
mobile-app/app/components/__snapshots__/Tabs.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/CollateralsTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/LoansTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultStatusTypes.ts
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultStatusTag.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowMoreScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/components/RowThemeItem.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts
mobile-app/cypress/support/commands.ts
mobile-app/cypress/support/loanCommands.ts

/kind chore
1. Adds e2e tests for borrow more loan
2. Initial setup for vault health tags test
Fixes #

`e2e` - borrow more loan

---

shared/store/wallet.ts

display symbol for LP

---

shared/translations/languages/de.json

`translations` - de update

---

shared/translations/languages/de.json

Translation update for wallet address

---

mobile-app/app/components/skeletonLoaders/DexSkeletonLoader.tsx
mobile-app/app/components/skeletonLoaders/VaultSkeletonLoader.tsx
mobile-app/app/components/skeletonLoaders/__snapshots__/SkeletonLoader.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx

/kind feature
- To update skeleton loader of dex screen
- Update your pool pair action button
- Remove unnecessary margin of favourite button
- Refactor list card margin styling to parent
Fixes #1474

`dex screen` - update skeleton loader UI

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionTimeProgress.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/BatchCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/BidCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/PlaceBidScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultSectionTextRow.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
shared/translations/languages/zh-Hant.json

/kind fix
- Fix content from overflowing in bid card UI
- Add missing ZH translation in passcode faq
Fixes #1628 
Fixed #1144

`bid card` - fix content overflow

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/BrowseAuctions.tsx

/kind feature
- To include beta features when scrolling so auction card UI does not get cropped
Fixes #1733

`auction list` - include beta features banner when scrolling

---

shared/translations/languages/de.json

/kind chore
• Missing <space>
Fixes #

Translation (DE): Missing <space>

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/LanguageSelectionScreen.test.tsx.snap
shared/translations/index.ts
shared/types/website.ts

Added French lang support

---

shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Updated missing translations

---

shared/translations/languages/de.json

German translation update

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreen.tsx
mobile-app/cypress/integration/functional/wallet/dex/dex_features.spec.ts
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts

/kind chore
Add e2e for DEX (favorites and search) and loans search
Fixes https://github.com/DeFiCh/wallet/issues/1784

`e2e` - DEX features and loans search

---

mobile-app/app/components/TextRow.tsx
mobile-app/app/components/WalletAddressRow.tsx
mobile-app/app/components/__snapshots__/WalletAddressRow.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/ConfirmPlaceBidScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/__snapshots__/BalancesScreen.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/components/BalanceControlCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmBorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmPaybackLoanScreen.tsx

Ellipses mode for wallet address and vault Id

---

mobile-app/app/screens/AppNavigator/screens/Balances/components/AddressControlScreen.test.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/AddressControlScreen.tsx
mobile-app/cypress/integration/functional/wallet/balances/addresses.spec.ts

Updated address flaky test cases

---

mobile-app/app/components/skeletonLoaders/SkeletonLoader.test.tsx
mobile-app/app/components/skeletonLoaders/__snapshots__/SkeletonLoader.test.tsx.snap

Snapshot test for AddressSkeletonLoader and BrowseAuctionsLoader

---

mobile-app/app/components/OceanInterface/TransactionError.test.tsx
mobile-app/app/components/OceanInterface/TransactionError.tsx
mobile-app/app/components/OceanInterface/__snapshots__/TransactionError.test.tsx.snap
shared/contexts/__mocks__/NativeLoggingProvider.tsx

Added test case for transaction error

---

shared/contexts/DeFiScanContext.test.tsx
shared/contexts/DeFiScanContext.tsx
shared/contexts/__snapshots__/DeFiScanContext.test.tsx.snap

Added unit test case for DeFiScanContext

---

shared/store/loans.test.ts
shared/store/loans.ts

/kind feature
- To add unit test for loan redux store
Fixes #1782

`test` - add unit test for loan redux store

---

website/src/pages/api/v0/announcements.ts

removed announcements

---

mobile-app/app/components/WalletAccordion.test.tsx
mobile-app/app/components/__snapshots__/WalletAccordion.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionDetails.test.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionTimeProgress.test.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionedCollaterals.test.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/AuctionDetails.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/AuctionTimeProgress.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/AuctionedCollaterals.test.tsx.snap
shared/contexts/DeFiScanContext.test.tsx
shared/contexts/LanguageProvider.test.tsx
shared/contexts/ThemeProvider.test.tsx
shared/contexts/WhaleContext.test.tsx
shared/contexts/WhaleContext.tsx
shared/contexts/__snapshots__/LanguageProvider.test.tsx.snap
shared/contexts/__snapshots__/ThemeProvider.test.tsx.snap
shared/contexts/__snapshots__/WhaleContext.test.tsx.snap

Test case updates

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/BatchCard.test.tsx.snap
mobile-app/app/screens/PlaygroundNavigator/PlaygroundScreen.tsx
mobile-app/app/screens/PlaygroundNavigator/components/PlaygroundStatus.tsx
mobile-app/app/screens/PlaygroundNavigator/sections/PlaygroundOperations.tsx
mobile-app/app/screens/PlaygroundNavigator/sections/PlaygroundToken.tsx
mobile-app/app/screens/PlaygroundNavigator/sections/PlaygroundUTXO.tsx
mobile-app/cypress/integration/functional/wallet/auctions/auctions.spec.ts
mobile-app/cypress/support/loanCommands.ts

/kind chore
Initial setup of auctions e2e. Vault gets liquidated and checked if they are displayed on auctions page.
Fixes #

`e2e` - auctions

---

shared/translations/languages/de.json

/kind chore
• Update translation: DE

Translation (DE): update translation

---

mobile-app/cypress/integration/functional/wallet/auctions/auctions.spec.ts

/kind feature
- To replace arbitrary loan amount by using calculated amount
- To replace fixed for loop iteration with recursive function
Fixes #

`e2e` - optimize and improve efficiency of vault liquidation

---

shared/translations/languages/fr.json

/kind fix
Correct some mistranslation

French translation correction

---

mobile-app/cypress/support/index.ts

/kind fix
- This should be able to fix all the failing tests caused by url stack on cypress tests.  This is still a workaround and still looking at the root cause of the issue
Fixes #

Fix failing tests on cypress

---

mobile-app/app/components/icons/assets/__snapshots__/index.test.tsx.snap
mobile-app/app/components/icons/assets/index.test.tsx

/kind fix
- Wrapping `getNativeIcon` inside the provider to fulfill react hooks requirement - called inside a component + provider
Fixes #

Fix unit tests on icon update

---

eas.json

bump node version on `eas` build

---

website/src/pages/api/v0/announcements.ts
website/src/pages/api/v0/settings/flags.ts

/kind chore
Remove auctions beta flag for 1.0.0 and added announcement
Fixes #1948

remove auctions beta flag

---

website/src/pages/api/v0/settings/flags.ts

/kind fix
Updated incorrect flags for auctions
Fixes #

fix(website-api): updated incorrect flag

---

shared/types/website.ts
website/src/pages/api/v0/announcements.ts

/kind feature
- To add `id` to the announcement api response
- To update ZH translation for new auction announcement
Fixes #

feat(api): add id to announcement

---

.github/workflows/eas-publish.yml

/kind chore
Allow eas builds on pre-release to avoid flooding official releases
Fixes #

allow eas builds on pre-release

---

.github/semantic.yml
.github/workflows/pr-lint.yml

/kind chore
Added a workflow to validate PR titles based on [conventional commits guidelines](https://www.conventionalcommits.org/en/v1.0.0/). Using this [GH actions](https://github.com/amannn/action-semantic-pull-request) to run this workflow. 
For title, we will be using a custom one to not use a short form like `feat` and `perf`. We will use clearer terms so it's easier to understand (feature and performance) especially for new developers.
Lower case is enforced for subjects. Only PR title is checked since commits will be squashed. In the event where there's only one commit, this workflow will run on that single commit.
Important thing to note, it will only be run via GH actions and not on commit level (locally) so other open source developers can easily commit via online tools (Online …

chore(workflow): add semantic check on title

---

mobile-app/app/contexts/FeatureFlagContext.tsx

/kind fix
Fixed issue where beta menu still displayed even if it doesn't satisfy the current version
Fixes #1962

fix(ui-ux): beta menu still displayed on non app version

---

website/src/pages/api/v0/announcements.ts

chore: Removed auctions announcement

---

shared/translations/languages/fr.json

/kind chore
Fixes #
typos, translation improvements

chore(translations): update fr.json translation improvements

---

shared/translations/languages/de.json

/kind chore
• Update translation (DE)

chore(translations): update DE

---

shared/translations/languages/de.json

chore(Translation): update DE

---

shared/translations/languages/fr.json

/kind chore
Fixes #
translation

Update fr.json Improving a formulation

---

website/src/pages/api/v0/announcements.ts

Revert "chore(api): Removed auctions announcement"

---

shared/types/website.ts
website/src/pages/api/v0/announcements.ts

chore(website): make french announcement optional

---

website/src/pages/api/v0/announcements.ts

chore(translations): french translation for announcements

---

shared/translations/languages/fr.json

/kind chore
Fixes #
4 missing {, typos, grammar
Spelling of initial letters according to French grammar rules

Update fr.json Corrections of upper and lower case spelling

---

.vscode/settings.json

/kind chore
Add menu title color for VSC to differentiate from other projects
Fixes #

chore(assets): add vsc menu title color

---

mobile-app/app/screens/AppNavigator/screens/Balances/hooks/TokenPrice.test.tsx

/kind chore
- To ensure that the useTokenPrice is calculating the the prices/ price rates and getting the relevant pairs
Fixes #1975

test(unit-tests): Add unit test for token price hook

---

mobile-app/app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
mobile-app/cypress/integration/functional/wallet/balances/send.spec.ts

/kind fix
- To handle enable/disable of token selection on send screen
Fixes #2004

fix(ui-ux): disable token selection if there is no balance in send screen

---

mobile-app/cypress/integration/functional/wallet/balances/balances.spec.ts

/kind fix
- To add tests for DFI USD balance
Fixes #

test(e2e): add tests for dfi usd balance

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx

feature(ui-ux): update slippage tolerance to 1%

---

website/src/pages/api/v0/announcements.ts

chore(translations): updated announcement translation for german language

---

shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

chore(translations): translation update

---

shared/translations/languages/de.json

/kind chore
Fixes #
correction typos

Update de.json standardization, correction

---

mobile-app/app/components/BottomSheetTokenList.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/__snapshots__/BalancesScreen.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/components/DFIBalanceCard.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/__snapshots__/DFIBalanceCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx

/kind fix
Fixes #2036
Partially #2019 (Edge case not yet handled)

fix(ui-ux): display USD value for LP tokens on Send page, balances re-alignment

---

shared/translations/languages/de.json

/kind chore
Fixes #
typo, wording, missing translation

Update de.json Improvement wording

---

shared/translations/languages/fr.json

Update fr.json standardization

---

docker-compose.yml

`DeFiCh/Jellyfish`, `DeFiCh/Whale` and `DeFiCh/Playground` should be compatible with `defid:2.6.0` without additional changes. We are working on releasing the jellyfish SDK.
- https://github.com/DeFiCh/playground/pull/379
- https://github.com/DeFiCh/whale/pull/735
- https://github.com/DeFiCh/jellyfish/pull/947

build(deps): docker-compose.yml to defid:2.6.0

---

website/src/pages/api/v0/announcements.ts

chore(website): update announcements to display block rewards

---

docker-compose.yml

chore(workflow): update fork height on docker-compose for defid

---

shared/translations/languages/fr.json

Update fr.json corrections

---

shared/translations/languages/de.json

/kind chore
Fixes #
Content errors

Update de.json improvements to the formulations

---

mobile-app/app/screens/AppNavigator/screens/Loans/hooks/LoanPaymentTokenRate.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
- Update calculations for converting pay amount in DUSD loans paid by DFI
- Fix Continue button disabled when choosing DFI
Fixes #

fix(core): update payback loan computations

---

.github/governance.yml
.github/labels.yml

chore(workflow): added time and priority labels

---

shared/translations/languages/de.json

/kind chore
Fixes #
unclear expressionss

Update de.json Making expressions more understandable

---

website/src/pages/api/v0/announcements.ts

chore: updated announcements

---

website/src/pages/api/v0/announcements.ts

chore(translations): added german translations

---

website/src/pages/api/v0/announcements.ts

chore(translations): updated to new announcements

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/PaymentTokenCards.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/hooks/LoanPaymentTokenRate.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts

/kind chore
- Fixes the bug with resulting balance
- Add e2e tests
Fixes #2103

test(e2e): payback loan by dfi

---

website/src/pages/api/v0/announcements.ts

chore(translations): FCH live

---

mobile-app/app/screens/AppNavigator/screens/Auctions/helpers/ActivePrice.ts
mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatioDisplay.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/hooks/NextCollateralizationRatio.ts
mobile-app/cypress/integration/functional/wallet/loans/vault_detail.spec.ts

/kind fix
- To use `next` price from price oracle when calculating next collateralization ratio
Fixes #2169

fix(ui-ux): next col ratio calculation in health bar

---

.github/workflows/ci-e2e.yml

/kind chore
Add two additional machines for cypress testing
Fixes #

build(workflow): add 2 concurrent cypress machines

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/AddOrRemoveCollateralForm.tsx
mobile-app/cypress/integration/functional/wallet/loans/collateral.spec.ts

/kind fix
- This will display N/A if the the resulting collateralization is invalid (negative, infinity, NaN)
Fixes #2117

fix(ui-ux): display n/a if resulting col is invalid

---

mobile-app/app/screens/ConnectionBoundary/ConnectionBoundary.tsx
mobile-app/app/screens/ConnectionBoundary/__snapshots__/ConnectionBoundary.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
Add a manual reconnect button to retry the connection so that users don't have to restart the app
Fixes #2149

feature(ui-ux):  `offline screen` - add manual reconnect

---

shared/translations/languages/fr.json

/kind chore
Fixes #
replacement of a misnomer

Update fr.json improvement

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
Fixes missing translation on the DEX page on swapping
Fixes #2108

chore(translations): `DEX` - Swapping Missing translation (DE, FR, ZHT, ZHS)

---

mobile-app/App.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BrowseAuctions.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/hooks/TokenPrice.ts
mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx
shared/contexts/StatsProvider.tsx
shared/contexts/WalletDataProvider.tsx

/kind chore
Improves performance of Auctions page
Currently, we call `fetchPoolPairs` on `useTokenPrice` hook. This results into multiple API fetching and re-rendering when this hook is called. To solve this, we will now call `fetchPoolPairs` on the StatsProvider so it's only called once. The rest will just rely on the selector to get updated values.
Second change, is to load only 5 auctions at start. Once end is reached, it will add 5 more. This is to minimize rendering and improve performance on cold starts
Fixes #

feature(ui-ux): auctions improvements

---

shared/translations/languages/de.json

/kind chore
Fixes #
typo, improve terms

Update de.json standardization of terms

---

shared/translations/languages/zh-Hans.json

/kind chore
- To update zhs translations for button group components for new DEX screen
Fixes #

chore(translations): update ZHS entries for button group label

---

package-lock.json

chore(deps): bump expo deps

---

mobile-app/app/screens/TransactionAuthorization/TransactionAuthorization.tsx

/kind chore
Removed useCallback for Passcode Prompt. Might be the cause of intermittent display issue on Android
Fixes #

feature(ui-ux): remove use callback on TX auth

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/CollateralTokenItemRow.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/AuctionedCollaterals.test.tsx.snap

/kind feature
Currency displayed needs to be consistent throughout the screen. This PR removes the 'USD' unit under collateral tokens and addition of '$'.
Fixes #2213

feature(ui-ux): auctions- inconsistent currency unit displayed

---

shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
Add translations for vault button
Fixes #2236

chore(ui-ux): `Loans` - vault - missing translation de

---

shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
Corrects spelling for DE Confirm Payment button.
Fixes #2257

chore(ui-ux): loans - `CONFIRM PAYMENT` button incorrect spelling (DE)

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/QuickBid.tsx
package-lock.json
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
Remove s in "auction": "Place a bid on the auctions with the min. next bid"
Fixes #2034

feature(ui-ux): grammar error: Remove s for "Auction" in quick bid drawer

---

mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PoolPairCards.tsx

fix(ui-ux): remove animation causing issues

---

mobile-app/app/screens/AppNavigator/screens/Dex/components/ButtonGroup.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/APRSection.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PoolPairCards.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PoolPairTextSection.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/__snapshots__/ButtonGroup.test.tsx.snap

/kind fix
Fixes https://github.com/DeFiCh/wallet/issues/2289

fix(ui-ux): wrapping of APR and button group

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/PaymentTokenCards.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/hooks/LoanPaymentTokenRate.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
- Remove capping of max button - MAX = max loan to pay, 50% = half of loan to pay
- Refactor paymentTokens to calculate on load instead of on demand (useMemo) - this was initially modified to be able to `disable` the payment tokens if balance is not enough. Disabling buttons has been scratched out but kept the implementation because it will be still useful in future iteration as discussed with @jtlntno-des e.g displaying amount in the payment token card
Fixes #2272

feature(core): update payback loan max behaviour

---

.github/workflows/defichain-dependencies.yml

/kind chore
With https://github.com/DeFiCh/wallet/pull/2325 merged in, we can consolidate the bumping workflow into one.

chore(core): consolidate playground bumping in defichain-dependencies.yml

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/QuickBid.tsx

/kind fix
- Pass display symbol to show correct icon
Fixes #2328

fix(ui-ux): pass display symbol

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/AddOrRemoveCollateralForm.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmEditCollateralScreen.tsx
mobile-app/cypress/integration/functional/wallet/loans/collateral.spec.ts
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
To display 0.00% when removing the max amount of collateral when there are more than 1 collaterals in total.
To display N/A when removing the max of the same existing collateral when there is only 1 collateral in total.
Fixes #2361

fix(ui-ux): `vault share` - display default values on 0 or max amount

---

package-lock.json

chore(deps): bump packages

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx

/kind fix
The max value for Non-DUSD Loans should be the :
- Outstanding balance if available balance is enough,
- Max available balance if available balance is not enough
Fixes #2351

fix(core): change payback loan's max to available amount if balance is not enough

---

mobile-app/app/screens/AppNavigator/screens/Loans/hooks/VaultShare.ts

/kind fix
Fixes https://github.com/DeFiCh/wallet/issues/2372

fix(ui-ux): set min value of vault share to 0%

---

package-lock.json

chore(deps): bump expo packages

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts

/kind fix
- Display payment tokens regardless if the user has a DUSD
Fixes #2366

fix(core): display payment tokens even if no balance

---

shared/translations/languages/fr.json

fix(translations): updated

---

shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

fix(translations): fixed translation for portfolio

---

shared/translations/languages/fr.json

fix(translations): fixed FR translation for locked in vault(s)

---

shared/translations/languages/fr.json

/kind chore
Fixes #
Grammatical form corrected

chore(translations): updated fr.json

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PoolPairCards.tsx

/kind refactor
Refactor the filter logic in DexScreen.tsx and PoolPairCards.tsx
It should only be implemented once and reused.
Fixes #2340 
- [x ] Read your code changes at least once
- [x ] Tested on iOS/Android device (e.g, No crashes, library supported etc.)
- [x ] No console errors on web

refactor filter logic in DexScreen

---

mobile-app/cypress/integration/functional/wallet/balances/announcements.spec.ts

chore(e2e): announcements banner update

---

docker-compose.yml
package-lock.json

chore(deps): bump deps

---

mobile-app/app/screens/AppNavigator/screens/Balances/components/BalanceCard.tsx

/kind feature
Update sorting icon on portfolio page
Fixes #

feature(ui-ux): update sorting icon

---

website/src/pages/api/v0/settings/flags.ts

feature(website-api): update local storage api to public

---

mobile-app/app/components/themed/ThemedSectionTitle.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/VaultDetailScreen.tsx

/kind chore
Ensure theme consistency in vault component 
Fixes #2474

chore(ui-ux): `loans` - light theme inconsistency

---

mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/AddressSelectionButton.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/BottomSheetAddressDetail.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/CreateOrEditAddressLabelForm.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/__snapshots__/AddressSelectionButton.test.tsx.snap

/kind fix
- To display flexible width on address selection button
Fixes #

fix(ui-ux): set min & max width for AddressSelectionButton

---

mobile-app/app/screens/AppNavigator/screens/Balances/components/CreateOrEditAddressLabelForm.tsx
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

feature(ui-ux): updated translations

---

docker-compose.yml

chore(deps): bump node to 2.7.0

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

chore(deps): flags for dusd 50%

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

/kind feature
- To have DUSD payment flag for payback loans
Fixes #

feature(core): add flags for dusd payment

---

mobile-app/app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/AddOrEditAddressBookScreen.tsx

/kind fix
- To remove `hasBottomSheet` from input field in `AddOrEditAddressBookScreen`
Fixes #

fix(ui-ux): remove hasBottomSheet option

---

mobile-app/app/screens/AppNavigator/screens/Balances/components/TotalPortfolio.tsx
mobile-app/cypress/integration/functional/wallet/balances/balances.spec.ts
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
Fixes https://github.com/DeFiCh/wallet/issues/2550

feature(ui-ux): subtract loans amount on total portfolio

---

mobile-app/cypress/integration/functional/wallet/balances/tokenDetail.spec.ts

feature(ui-ux): update e2e

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanPercentage.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/PaymentTokenCards.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
- Fixes penalty payment token display
- Fixes moving component on mobile devices when toggling resulting col in payback loan screen
Fixes #2549

fix(core): change 1 percent payment fee

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx

/kind fix
- Scroll issue in payback loan
Fixes #

fix(ui-ux): scroll in paybackloan

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/LoansFaq.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/__snapshots__/LoansFaq.test.tsx.snap

/kind fix
faq translation fix
Fixes #

fix(ui-ux): faq translation fix

---

mobile-app/app/screens/AppNavigator/screens/Balances/screens/AddressBookScreen.tsx

/kind fix
- To hide edit button when addressbook is empty
Fixes #

fix(ui-ux): hide edit button when no address

---

mobile-app/app/screens/AppNavigator/screens/Dex/hook/SwappableTokens.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
Fixes https://github.com/DeFiCh/wallet/issues/2562
Fixes https://github.com/DeFiCh/wallet/issues/2567

fix(ui-ux): translations, sorting and dBURN

---

website/src/pages/api/v0/settings/flags.ts

feature(core): flags

---

shared/translations/languages/de.json

/kind chore
Fixes #
Typo capitalization noun

chore(translations): updated de.json

---

mobile-app/app/components/InputHelperText.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/components/BalanceCard.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SlippageTolerance.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/ButtonGroup.tsx

/kind feature
- Re-position slippage tolerance
- Bg color of button group in dark mode
- Label UI of available text
- Vertical centering oracle price row
Fixes #

feature(ui-ux): minor update on UI in swap screen

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/AddOrRemoveCollateralForm.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/hooks/CollateralPrice.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx

/kind fix
Allow removal of collaterals if there are no loans in the vault yet
Fixes #2597

fix(core): allow removal of col if no loans

---

website/src/pages/api/v0/settings/flags.ts

chore(deps): bump jellyfish

---

mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/KnowledgeBaseScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/KnowledgeBaseScreen.test.tsx.snap

fix(ui-ux): token detail redirect

---

website/src/pages/api/v0/announcements.ts
website/src/pages/api/v0/settings/flags.ts

chore(website-api): update flags and announcements

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SlippageTolerance.tsx

Due to difficulties in custom styling
/kind refactor
- Create a new component to handle target token row display due to difficulties in custom UI styling
- Fix spacing of text display when entering swap screen without any token selected
- Fix target token input number does not reset when "from token" input is cleared
- Fix slippage tolerance spacing
Fixes #
- Known issue: upon toggling custom slippage tolerance,  vertical spacing of target token input row changes

refactor(ui-ux): TargetTokenRow from TokenRow

---

.github/workflows/oss-governance-bot.yml

chore(workflows): update oss-governance-bot.yml to use new package

---

docker-compose.yml
package-lock.json

chore(deps): bump dependencies

---

mobile-app/app/components/__snapshots__/InputHelperText.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.test.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/__snapshots__/BalancesScreen.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/screens/FutureSwapDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/FutureSwapScreen.tsx
shared/store/futureSwap.ts
shared/store/index.ts
shared/store/loans.ts

/kind feature
- To add partial integration for `getFutureSwapBlock`, `getPendingFutureSwaps`
- Update UI to exclude field that does not have data to display
Fixes #

feature(api): add partial api integration

---

mobile-app/app/screens/AppNavigator/screens/Loans/hooks/LoanPaymentTokenRate.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/cypress/integration/functional/wallet/loans/loans.spec.ts

fix(core): dfi conversion on payback loan

---

docker-compose.yml
mobile-app/app/contexts/PlaygroundContext.tsx
mobile-app/cypress/integration/functional/wallet/auctions/auctions.spec.ts
mobile-app/cypress/integration/functional/wallet/balances/addresses.spec.ts
mobile-app/cypress/integration/functional/wallet/balances/send.spec.ts
package-lock.json
shared/contexts/WhaleContext.test.tsx
shared/contexts/WhaleContext.tsx
shared/contexts/__snapshots__/WhaleContext.test.tsx.snap

chore(deps): bump dependencies and update playground URL

---

mobile-app/app/screens/AppNavigator/screens/Balances/BalancesNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/AddOrEditAddressBookScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/AddressBookScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
mobile-app/cypress/integration/functional/wallet/balances/send.spec.ts
mobile-app/cypress/integration/functional/wallet/settings/settings.spec.ts
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
- To remove list header and list footer when address book is empty
- To add `ADD ADDRESS` button in empty address book
- To select the new address automatically after adding new address
Fixes #
- ~Will add translation and e2e later~
- Address will be selected automatically when sending tokens iff. user is adding a new address and has completed the action of saving an address to the address book.

feature(ui-ux): update empty address book UI and auto select address on successful add

---

docker-compose.yml
package-lock.json

chore(deps): bump

---

docker-compose.yml
package-lock.json

Revert "chore(deps): bump"

---

docker-compose.yml
package-lock.json

Revert "Revert "chore(deps): bump""

---

eas.json

chore(deps): fix deployment

---

mobile-app/app/screens/AppNavigator/AppNavigator.tsx
shared/contexts/WalletDataProvider.tsx

/kind
Issue: Retrieving address from `WalletContext`
Component Structure: `App -> Main -> RootNavigator -> AppNavigator`
WalletContext is only available from the children of RootNavigator, but the PR calls it in `App`
Solution: Move the fetchTokens down from RootNavigator to AppNavigator
Fixes #

feature(core): move the fetch tokens down to app nav

---

mobile-app/app/screens/AppNavigator/screens/Balances/screens/AddressBookScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
- To add translatons for `GENERAL` and `Add New Address`
Fixes #

chore(translations): add address translations

---

mobile-app/app/components/TokenIconGroup.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/AddOrRemoveCollateralForm.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultInfo.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultInfo.test.tsx.snap

/kind fix
- To offset the spacing created by relative position of TokenIconGroup 
Fixes #2739

fix(ui-ux): right spacing created by relative position of TokenIconGroup 

---

shared/translations/languages/it.json

fix it translation

---

shared/translations/languages/de.json

/kind chore
The PR fixes some typos, improves some formulations and harmonises spelling in the German language file.
Fixes #

improvements in the German language file

---

.github/workflows/defichain-dependencies.yml

chore(workflows): add required Create PR token to trigger workflows

---

mobile-app/app/screens/AppNavigator/screens/Balances/components/DFIBalanceCard.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx

token detail - reenable for DFI #2395

---

mobile-app/app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/FutureSwapScreen.tsx
shared/store/futureSwap.ts

/kind feature
- To update future swap list view UI
Fixes #

feature(ui-ux): update future swap list view UI

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx

fix(ui-ux): allow manage loans on halt state

---

.github/workflows/eas-publish.yml

chore(core): remove new workflow

---

babel.config.js
docker-compose.yml
mobile-app/app/api/wallet/mnemonic_storage.ts
mobile-app/app/api/wallet/provider/mnemonic_encrypted.ts
mobile-app/app/api/wallet/provider/mnemonic_unprotected.ts
mobile-app/app/screens/ErrorBoundary/ErrorBoundary.tsx
package-lock.json
package.json

chore(core): fix for iOS breaking

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexRemoveLiquidity.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PoolPairCards.tsx
mobile-app/cypress/integration/functional/wallet/dex/remove_liquidity.spec.ts

Price Rates - order of token display #2735
Co-authored-by: JJ Adonis <josejaimecareers@gmail.com>
/kind feature
Fixes #

feature(ui-ux): price rates - order of token display

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
- Some translations were split (for styling) to multiple ones in the code, this was merged to one translation and removed the styling because it has different meaning when translated in split
- Add more translations
Fixes #

chore(translations): add future swap translations

---

mobile-app/app/components/BottomSheetTokenList.tsx
mobile-app/app/components/NumberRow.tsx
mobile-app/app/components/__snapshots__/NumberRow.test.tsx.snap
mobile-app/app/components/__snapshots__/TransactionResultsRow.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/components/__snapshots__/AuctionDetails.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/screens/ConfirmWithdrawFutureSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/WithdrawFutureSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/EditCollateralScreen.tsx
mobile-app/cypress/integration/functional/wallet/dex/futureswap.spec.ts

/kind fix
- Remove all oracle price indicator in withdraw and future swap
- Remove oracle price indicator on swap bottom sheet
- Revert space code on number row to fix spacing
- Change to be confirmed to Oracle Price +-5%
- Modify e2e
- Fix ui issue when changing the `To` token from loan token to crypto (stucked at future swap option)
Fixes #

fix(core): future swap minor fix

---

website/src/pages/api/v0/announcements.ts

chore(ui-ux): updated announcements

---

mobile-app/app/components/InfoRow.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/FutureSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
- Change execution block to settlement block
Fixes #

chore(ui-ux): change execution to settlement

---

shared/translations/languages/es.json

/kind chore
- Update portfolio on es translation
Fixes #

chore(translations): update portfolio on es

---

mobile-app/app/screens/WalletNavigator/screens/components/OnboardingCarousel.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
Updated onboarding welcome text
Fixes #

chore(ui-ux): updated onboarding welcome screen text

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx

/kind fix
- Fix for instant swap  on dToken <-> DUSD
Fixes #

fix(core): use correct boolean on navigate confirm

---

mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx

fix(ui-ux): incorrect calculation for swap

---

website/src/pages/api/v0/announcements.ts

chore(ui-ux): update announcements

---

mobile-app/app/components/HeaderSearchInput.tsx
mobile-app/app/components/SearchInput.test.tsx
mobile-app/app/components/SearchInput.tsx
mobile-app/app/components/__snapshots__/HeaderSearchInput.test.tsx.snap
mobile-app/app/components/__snapshots__/SearchInput.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Balances/screens/AddressBookScreen.tsx

feature(ui-ux): Added search box and create new address icon

---

mobile-app/cypress/integration/functional/wallet/dex/remove_liquidity.spec.ts

fix(e2e): updated failing remove liquidity e2e test case

---

.github/workflows/jellyfish-dependencies.yml

With https://github.com/JellyfishSDK/jellyfish/issues/580 resolved, the dependencies has been consolidated and released together.

chore(workflow): consolidate jellyfish dependencies bumping

---

website/src/pages/api/v0/announcements.ts

chore(ui-ux): update announcement for dAMZN Stock Split

---

website/src/pages/api/v0/announcements.ts

chore(ui-ux): updated announcement

---

mobile-app/app/screens/AppNavigator/screens/Balances/screens/AddressBookScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

chore(translations): added missing translations

---

website/src/pages/api/v0/announcements.ts

chore(website-api): remove announcements

---

package-lock.json
package.json

chore(deps): bump expo dependencies

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

feature(core): add remote and local flag for service provider

---

website/src/pages/api/v0/settings/flags.ts

/kind chore
Enable on all env
Fixes #

chore(core): enable custom provider on all env

---

mobile-app/app/components/TokenIconGroup.tsx

loans - active loans values overflow in vault card #2847

---

website/src/pages/api/v0/settings/flags.ts

chore(core): flag service provider as beta

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/ServiceProviderScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

feature(ui-ux): update translations and text

---

mobile-app/app/screens/AppNavigator/screens/Auctions/screens/PlaceBidScreen.tsx

fix(ui-ux): ui fix 1.14.0

---

mobile-app/app/hooks/useCachedResources.ts
mobile-app/app/tailwind.ts
package-lock.json
package.json

Add font-*-v2 tailwind classes
/kind feature
- To add sora font and `font-*-v2` tailwind classe
Fixes #

feature(assets): add sora font

---

shared/translations/languages/de.json
shared/translations/languages/fr.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
Missing `.` for languages DE, FR, ZHS, ZHT
Fixes #

Translation: Missing <.> in Payback loan screen

---

mobile-app/app/components/IconButton.test.tsx
mobile-app/app/components/IconButton.tsx
mobile-app/app/components/themed/ThemedIcon.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexGuidelines.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/ActionSection.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/ScrollableButton.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Transactions/TransactionsScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Transactions/screens/stateProcessor.ts
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateWalletGuidelines.tsx

feature(ui-ux): feather icon support

---

mobile-app/app/styles.json
mobile-app/app/tailwind.config.js

fix(ui-ux): updated orange shade for v2 design

---

docker-compose.yml
package-lock.json

chore(deps): bump expo

---

mobile-app/app/constants/ThemeV2.ts
mobile-app/app/screens/WalletNavigator/screens/components/OnboardingCarouselV2.tsx

/kind fix
- To set the very thin border color under header title
- To fix design system color update regression on existing component 
Fixes #

fix(ui-ux): add border color to theme v2

---

website/src/pages/api/v0/settings/flags.ts

chore(website-api): bump to public

---

mobile-app/cypress/e2e/smoke/smoke.spec.ts

fix(e2e): fixed restore wallet failing test case

---

mobile-app/app/components/WalletTextInputV2.tsx

fix(ui-ux): updated clear btn icon size

---

mobile-app/app/screens/WalletNavigator/WalletNavigator.tsx

/kind
- To fix wrapped network name at header title
Fixes #

fix(ui-ux): fix wrapped network name

---

mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateWalletGuidelinesV2.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/PinConfirmationV2.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/VerifyMnemonicWalletV2.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/CreateWalletGuidelinesV2.test.tsx.snap
package-lock.json
shared/translations/languages/de.json
shared/translations/languages/fr.json

Signed-off-by: Suraj Auwal <siradjiawoual@gmail.com>
/kind chore
Fixes #

chore(translations): added FR and DE translations from Onboarding V2

---

website/src/pages/api/v0/announcements.ts

/kind chore
Revert announcements.

chore(announcements): revert announcements

---

mobile-app/app/screens/WalletNavigator/screens/CreateWallet/PasscodeFaq.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/PasscodeFaq.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

chore(ui-ux): missing translations

---

mobile-app/app/components/HeaderNetworkStatus.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateWalletGuidelinesV2.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/PinCreationV2.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/WalletCreateRestoreSuccess.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/CreateWalletGuidelinesV2.test.tsx.snap
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/WalletCreateRestoreSuccess.test.tsx.snap
mobile-app/app/screens/WalletNavigator/screens/components/LearnModeCTA.tsx
mobile-app/cypress/e2e/functional/onboarding/createMnemonicWalletV2.spec.ts
mobile-app/cypress/e2e/functional/onboarding/onboardingV2.spec.ts
mobile-app/cypress/e2e/functional/onboarding/restoreV2.spec.ts
mobile-app/cypress/e2e/smoke/smokeV2.spec.ts
mobile-app/cypress/support/commands.ts
mobile-app/cypress/support/onboardingCommandsV2.ts

feature(e2e): added e2e for onboarding v2

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
shared/store/wallet.ts
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

feature(ui-ux): display DEX stabilization fee

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

feature(website-api): added setting v2 flag for settingv2 onboarding

---

mobile-app/app/components/WalletTextInputV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/SettingsScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/components/ResetButtonV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/KnowledgeBaseScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/LanguageSelectionScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/RecoveryWordsScreenV2.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/CreateMnemonicWalletV2.tsx
mobile-app/app/styles.json
mobile-app/app/tailwind.config.js

/kind chore
In this PR we added new border radius configuration for version 2 design.
1. `lg-v2`: 10px
2. `xl-v2`: 15px
3. `2xl-v2`: 20px
Fixes #

chore(ui-ux): added lg-v2 and xl-v2 border radius style

---

mobile-app/app/components/BottomSheetInfo.tsx
package-lock.json

/kind fix
Fixes #3139
Fixes #2850

fix(ui-ux): bottom sheet slowness

---

mobile-app/app/screens/AppNavigator/screens/Settings/SettingsScreenV2.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

fix(ui-ux): minor text casing and layout issue

---

mobile-app/app/contexts/__mocks__/FeatureFlagContext.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/ManageBids.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetail.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/FeatureFlagScreen.test.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/FeatureFlagScreen.test.tsx.snap
mobile-app/cypress/e2e/functional/wallet/settings/featureGate.spec.ts
mobile-app/cypress/e2e/functional/wallet/settings/knowledgeBase.spec.ts
shared/contexts/WalletDataProvider.tsx
shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

chore(ui-ux): cleanup flags

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/ServiceProviderScreenV2.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

fix(ui-ux): missing translations

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ReceiveScreen.tsx

fix(ui-ux): `receive` screen fix qr code

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/GetDFIScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ReceiveScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/__snapshots__/GetDFIScreen.test.tsx.snap

/kind fix
- Fix wallet address copy button disappearing on certain devices
- Fix wallet address overflow issue
Fixes #

fix(ui-ux): wallet address issue

---

shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind chore
- To add DE, FR and ES translations for change passcode v2 screen
Fixes #

chore(translations): add entries for change passcode screen

---

mobile-app/app/screens/AppNavigator/screens/Settings/components/RowLanguageItem.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/LanguageSelectionScreen.test.tsx.snap

/kind fix
Fixing tick icon size on the language screen
Fixes #

fix(ui-ux): language screen tick icon

---

mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx

fix(ui-ux): add bottom tab

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokensVsUtxoFaqV2.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/__snapshots__/TokensVsUtxoFaqV2.test.tsx.snap

fix(ui-ux): change to bulleted list

---

mobile-app/app/components/WalletTextInputV2.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/AddOrEditAddressBookScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/AddressBookScreenV2.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

chore(ui-ux): added missing translations

---

mobile-app/app/screens/AppNavigator/screens/Settings/SettingsScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/components/RowThemeItemV2.tsx

fix(ui-ux): padding on android

---

mobile-app/app/screens/AppNavigator/screens/Settings/components/RowThemeItemV2.tsx

fix(ui-ux): update theme row

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

feature(website-api): add portfolio 2.0 feature flag

---

shared/translations/languages/de.json

Translation (DE): Current translation for "LP Token" breaks UI #2535

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

fix(core): revert previous flag name

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/FutureSwapScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
- To display executed block info to the user
Fixes #

feature(ui-ux): add info text in future swap list

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/LanguageSelectionScreen.test.tsx.snap
shared/translations/index.ts

/kind fix
- To update label of zht in language selection screen
Fixes #

fix(ui-ux): label of zht in language select

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts

/kind fix
- Move the dex stabilization fee to the dex stabilization hook
- Fix display issue of the fee in composite swap
- Refactor composite swap logic to reduce clutter and redundant logic
Fixes #

fix(core): display of percentage and refactor dex stabilization hook

---

mobile-app/app/components/OceanInterface/OceanInterface.tsx
mobile-app/app/components/OceanInterface/TransactionCloseButton.tsx
mobile-app/app/components/OceanInterface/TransactionDetail.tsx
mobile-app/app/components/OceanInterface/TransactionError.tsx
mobile-app/app/components/OceanInterface/TransactionIDButton.tsx
mobile-app/app/components/OceanInterface/__snapshots__/TransactionError.test.tsx.snap
shared/store/ocean.ts
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind feature
Update Ocean Interface to version LW 2.0
Fixes #

feature(ui-ux): ocean Interface v2.0

---

mobile-app/app/components/OceanInterface/TransactionDetail.tsx

/kind fix
fix light mode on the ocean interface
Fixes #

fix(ui-ux): fix light mode on ocean interface

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/SettingsScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/components/RowThemeItemV2.tsx

fix(ui-ux): adjust network header and padding for settings

---

mobile-app/app/screens/AppNavigator/screens/Settings/SettingsScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/components/RowThemeItemV2.tsx

fix(ui-ux): simplify padding for settings on android

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx

fix(ui-ux): token detail top padding fix

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/__snapshots__/PortfolioScreen.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TotalPortfolio.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/__snapshots__/TotalPortfolio.test.tsx.snap

fix(ui-ux): align currency center

---

mobile-app/app/screens/AppNavigator/screens/Loans/hooks/CollateralizationRatio.ts

/kind fix
- To skip resulting CR when input amount is `0`
Fixes #

fix(ui-ux): skip calculation when input is 0

---

mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts

fix(core): display fee of dex stab fee

---

mobile-app/app/components/OceanInterface/TransactionCloseButton.tsx
mobile-app/app/components/OceanInterface/TransactionDetail.tsx
mobile-app/app/components/OceanInterface/TransactionError.tsx
mobile-app/app/components/OceanInterface/__snapshots__/TransactionError.test.tsx.snap

/kind feature
- Increase touch area of x button
Fixes #

feature(ui-ux): increase touch area of x in ocean interface

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/MarketplaceScreen.tsx

feature(ui-ux): remove hoo and hotbit

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

/kind chore
Add feature flagging for Add/Remove liquidity v2 and Send screen v2
Fixes #

chore(ui-ux): add feature flagging for 2.0 screens

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/__snapshots__/PortfolioScreen.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TotalPortfolio.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/__snapshots__/TotalPortfolio.test.tsx.snap

fix(ui-ux): fixed portfolio header thin line for android device

---

shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
Update missing translations for Convert v2 screen
Fixes #

fix(translations): update missing translation

---

website/src/pages/api/v0/settings/flags.ts

/kind chore
- To allow send v2 for internal testing
Fixes #

chore(website-api): set send v2 feature to public

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreenV2.tsx

/kind fix
- Improve UX of acknowledgement checkbox by adding onPress on its text
- Add more spacing around buttons on Send confirmation screen to follow the figma design
Fixes #

fix(ui-ux): reduce space and add on click on acknowledgement text of lp send

---

mobile-app/app/components/SummaryTitleV2.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreenV2.tsx
shared/store/wallet.ts

fix(ui-ux): remove cyclic issue

---

.github/CODEOWNERS
.github/workflows/pr-lint.yml

chore(docs): add codeowners and remove strict scope

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenSelectionScreen.tsx

fix(ui-ux): update send empty asset bg

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreenV2.tsx

fix(ui-ux): validate address issue

---

mobile-app/app/components/BottomSheetWithNav.tsx
mobile-app/app/components/BottomSheetWithNavV2.tsx
mobile-app/app/screens/TransactionAuthorization/PasscodePrompt.tsx

/kind fix
- Trial and error - fix. After adding/removing props, I noticed that when adding a custom handle, the very intermittent error is fixed. 
- How to replicate the issue? Quick Bid or anything that uses the useBottomSheet hook open and close multiple times
Fixes #

fix(ui-ux): potential fix for disappearing bottom sheet

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexConfirmRemoveLiquidityV2.tsx

/kind
Fix missing signer copy from confirm remove liquidity
Fixes #

fix(ui-ux): missing signer copy for remove liquidity

---

shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
- To fix DE and FR translation for future swap success message in transaction loader
- To fix DE and FR translations for `ASSETS` in portfolio screen
Fixes #

fix(translations): future swap success message and ASSETS 

---

website/src/pages/api/v0/announcements.ts

chore(api): birthday announcements

---

mobile-app/app/screens/PlaygroundNavigator/components/PlaygroundAction.tsx
mobile-app/app/screens/PlaygroundNavigator/sections/PlaygroundStatusInfo.tsx

fix(ui-ux): disable onPress on playground status info

---

mobile-app/app/screens/AppNavigator/screens/Dex/PoolPairDetailsScreen.tsx

/kind fix
- Fixes wrong suffix and price ratios in PoolPair details screen
- Adds network selection icon to poolPair details header
Fixes #

fix(ui-ux): pool pair details page minor fixes

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx

fix(dex): performance improvement for dex landing screen

---

mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/APRSection.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PriceRatesSection.tsx

/kind feature
- As title, to allow more accuracy of price rate when displaying
Fixes #

feature(ui-ux): reduce font size of price rate and APR

---

mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts

/kind fix
- Change approach by converting the pairs to nodes before checking if the direction is correct
Fixes #
**Given:** 
From: **dUSDT**, To: **dTSLA** 
Pairs with high dex fees: (DUSD -> DFI, DUSD- > dUSDC, DUSD -> dUSDT)
```
// no dex fee:  dUSDT -> DUSD
// with dex fee: DUSD -> dUSDT
bestPath: [dUSDT-*DUSD*] -> [*dTSLA*-DUSD] -- only returns pairs, not in right direction
```
- Change technical approach 
->  First, convert pairs[] to nodes[] in correct direction 
```pairs: [dUSDT-*DUSD*] -> [*dTSLA*-DUSD]```
-> Then from the nodes, check if the pairs with 
```nodes with direction: [dUSDT -> DUSD -> dTSLA]```
-> In this example, no high dex fees since it is `dUSDT -> DUSD `

fix(ui-ux): change tech approach on dex stab fee

---

.github/CODEOWNERS

Signed-off-by: JJ Adonis <josejaimecareers@gmail.com>
/kind chore
Fixes #

chore(docs): cleanup codeowners

---

shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

/kind feature
- add feature flag for composite swap version 2.0
Fixes #

feature(core): add feature flag for swap 2.0

---

mobile-app/app/screens/AppNavigator/screens/Auctions/helpers/precision-token-value.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TokenBreakdownDetailsV2.tsx

/kind fix
This pr fixes issue related to amount update not reflect after to currency switch on token detail screen
Fixes #

fix(ui-ux): fixed issue on token detail screen for amount update after switching currency

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TokenBreakdownDetailsV2.tsx

/kind fix
- To fix condition to display suffix that was introduced from #3374
Fixes #

fix(ui-ux): condition for tokenB suffix

---

website/src/pages/api/v0/announcements.ts

/kind chore
- Remove the announcements in LW but retain the ones in scan
Fixes #

chore(ui-ux): remove announcement in lw

---

website/next.config.js

chore(deps): redirect

---

shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

fix(translations): added missing translation for Slippage tolerance

---

mobile-app/app/screens/AppNavigator/screens/Auctions/components/QuickBid.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexRemoveLiquidity.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/AddLiquidityInputCard.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetail.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetailV2.tsx

chore(ui-ux): added typings and added useWalletAddress for bottom sheet address details

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/ConfirmPinScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
1. Remove trailing dot (.) on Change Passcode screen
2. Add missing translation for Closing Vault and Removing Liquidity screens
Fixes #

fix(ui-ux): add missing translations

---

mobile-app/app/screens/AppNavigator/screens/Dex/components/DexScrollable.tsx

fix(ui-ux): add dollar prefix to total liquidity in new pools

---

mobile-app/app/components/BottomSheetInfoV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SwapSummary.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

/kind fix
- Add translations for settlement modal in swap page and confirm page's transaction loaders (Still awaiting for some translations)
- Remove unused code from settlement component and adjust padding
Fixes #

fix(ui-ux): swap v2 fixes

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/SwapTokenSelectionScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/hook/SwappableTokensV2.ts

/kind chore
In swap token selection screen, display token name returned from API
Fixes #

chore(ui-ux): display token name in swap token selections list

---

.github/labeler.yml

chore(docs): updated governance

---

package-lock.json
package.json

chore(deps): bump cypress

---

mobile-app/app/screens/AppNavigator/screens/Dex/hook/SwappableTokensV2.ts

/kind fix
Filter out tokens with status=false in swap token list
Fixes #

fix(ui-ux): filter token list with status false

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx

/kind refactor
Refactor behaviour of input amount
Existing: input amount will only be enabled when both token A and B are selected
New: input amount will be enabled when token A is selected, regardless of token B is selected or not
Fixes #
Flow of autofocus input remains the same

refactor(ui-ux): input amount enable/disable behaviour

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/TokenDropdownButton.tsx

This PR fixes several UI issues on the new swap screen
- fix the wrong token symbol on the swap summary and confirmation screen
Fixes #

fix(ui-ux): fix UI on Swap screen v2

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/ConfirmCompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx

feature(core): add slippage in formula

---

mobile-app/app/components/WalletTextInputV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SlippageToleranceV2.tsx

Fix the following bug:
- Custom slippage sizing issue on both input and button
- Rectify the swap button symbol
Fixes #

fix(ui-ux): Composite swap bug fixes

---

website/src/pages/api/v0/settings/flags.ts

chore(core): bump description

---

website/src/pages/api/v0/settings/flags.ts

chore(core): use relative import

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SlippageToleranceV2.tsx

Fix issue where the sizing broke when there's error message on the custom slippage input.
Fixes #

fix(ui-ux): rectify slippage sizing bug

---

mobile-app/app/components/HeaderSearchInputV2.tsx
mobile-app/app/components/SearchInputV2.tsx

fix(ui-ux): fixed header search bar flicker issue and added in focus border

---

mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/LoansTab.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailTabSection.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.test.tsx
shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

feature(ui-ux): implemented bottom sheet for poof mechanism

---

website/src/pages/api/v0/settings/flags.ts

feature(api): set unloop feature flag to public

---

website/src/pages/api/v0/announcements.ts

- As titled, missing all translation except DE and FR
Fixes #

feature(api): add FCE announcement

---

website/src/pages/api/v0/settings/flags.ts

chore(flags): enable on mainnet

---

mobile-app/cypress/e2e/functional/wallet/loans/loans.spec.ts
mobile-app/cypress/e2e/functional/wallet/loans/vault_detail.spec.ts
mobile-app/cypress/support/loanCommands.ts

Update other test cases related to new create vault v2 flow
Fixes #

fix(e2e): update test cases related to create vault

---

app.json

Hermes - https://hermesengine.dev/
Expo - https://docs.expo.dev/guides/using-hermes/
Fixes #

feature(core): enable hermes

---

.github/CODEOWNERS

chore(docs): updated code owners

---

mobile-app/app/components/NumberRowV2.tsx
mobile-app/app/components/SummaryTitleV2.tsx
mobile-app/app/components/TextRowV2.tsx
mobile-app/app/components/TokenIconGroupV2.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/AuctionNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionVaultDetails.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BatchCard.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/hooks/AuctionTimeLeft.ts
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/AuctionDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/ConfirmPlaceBidScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/NetworkSelectionScreen.test.tsx.snap
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/OnboardingNetworkSelectScreen.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Updated Auction Details screen to follow V2 design
Fixes #

feature(ui-ux): update auction details screen to v2

---

mobile-app/app/components/skeletonLoaders/__snapshots__/SkeletonLoader.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Auctions/components/AuctionsSortRow.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BrowseAuctions.tsx

chore(ui-ux): removed sort for total collateral USD value in auctions

---

mobile-app/app/components/themed/ThemedFlashList.tsx

fix(ui-ux): fixed flash list warning for rendered size

---

mobile-app/app/screens/AppNavigator/screens/Auctions/AuctionScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/components/BrowseAuctions.tsx

- To allow flashlist to complete rendering
Fixes #

feature(ui-ux): extend auction loader display time

---

mobile-app/app/screens/AppNavigator/hooks/useNavigatorHeaderStylesOption.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCardsV2.tsx

- Fix the spacing at the side needs to match figma
- Fix the network icon that does not align to title on android
Fixes #

fix(ui-ux): resolve ui issue on loans screen

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCardsV2.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

feature(core): add loans search functionality

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanSchemeOptionsV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/CreateVaultScreenV2.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Update description to "Select a loan scheme for your vault." and collateral to "Min. collateral ratio"
Fixes #

chore(ui-ux): update create vault wording

---

mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreenV2.tsx

- Keep the components on the DOM to reduce rerendering time
Fixes #

feature(core): improve perf of tab switching

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCardsV2.tsx
mobile-app/cypress/e2e/functional/wallet/loans/loans.spec.ts

fix logic on search token input on loans screen
Fixes #

fix(ui-ux): resolve search input logic on token screen

---

mobile-app/app/components/SearchInputV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCardsV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/PriceOracleInfo.tsx

- Update search behaviour when there's no/have search results
- Make search input height same on web
- Add skeleton loader on first load 
Fixes #

fix(core): search behaviour and loading

---

mobile-app/app/components/TextRowV2.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/NetworkSelectionScreen.test.tsx.snap
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/OnboardingNetworkSelectScreen.test.tsx.snap

To fix the overlapping vault details in FR.
Fixes #

fix(ui-ux): fix overlapping text on smaller screen

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmEditLoanSchemeScreenV2.tsx
shared/translations/languages/es.json

fix(translations): add missing translations

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCardV2.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

fix(translations): rename existing loans in vault card

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SwapRowTo.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatioDisplayV2.tsx

feature(ui-ux): collateral ratio progress bar

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatioDisplayV2.tsx

fix(ui-ux): fixed collateral ratio display bar

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatioDisplayV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/AddOrRemoveCollateralScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmEditCollateralScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

- Add translation for add/remove collateral and confirm V2 screens
- Update error messages for Remove collateral
Fixes #

chore(translations): add translation for add/remove collateral v2

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetVaultList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx

Display checkmark beside selected vault on bottom sheet vault list when user decides to change vault.
Fixes #

feature(ui-ux): display selected vault indicator in borrow screen

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetVaultList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatio.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCardsV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

- Add missing translations on bottomsheet vault list
- Replace `Select Vault To Use` with just `Select Vault`
Fixes #

fix(translations): add missing translations on bottomsheet vault list

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetLoanTokensList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetVaultList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCardsV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultsV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Fixes #
1. Loans > Borrow tab> at any token, select Borrow > note: in bottom sheet, header and ⓧ baseline aligned
2. Loans > Your vaults tab > at any token, select Your vaults > note: in bottom sheet, header and ⓧ baseline aligned

feature(ui-ux): fixed header for loans bottom sheet

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx

- As titled, in borrow loan v2 validation
Fixes #

fix(ui-ux): rearrange error condition to take priority over warning

---

mobile-app/app/screens/TransactionAuthorization/api/transaction_types.ts

Update passcode loading and text messages for transaction authorization
Fixes #

feature(ui-ux): update passcode loading and text messages

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

This PR is for updating translation string for borrow loan tokens
Fixes #

chore(translation): update translation message for validation message for borrow-loan-token-screen

---

mobile-app/app/components/CollateralFactorTag.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailCollateralsRow.tsx

- The collateral factor should be displayed if it is not 1, reused the common component
Fixes #

feature(core): add col factor on vault detail

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetVaultList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx

- As titled, to be accurate to 2dp and consistent across other screens 
Fixes #

fix(ui-ux): use informativeRatio when displaying col ratio

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCards.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmPaybackLoanScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

This PR includes the following bug fixes for the v2.9.1 releases:
- resolved translation on cancel prompt
-  resolved translation on payback loan
-  fix token loan sort logic
Fixes #

fix(ui-ux):  resolve bug in v2.9.1

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/LoanCards.tsx

fix(ui-ux): loan card gutter

---

mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultActionButtons.tsx

- Fix cut icons in vault detail screen
Fixes #

fix(ui-ux): fix cut icons on vault detail screen

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultBanner.tsx

- Standardize button font size for 'Create a vault' and 'Add Collateral' in loans page to match with 'Swap button' on DEX page
Fixes #

fix(ui-ux): enlarge create vault font size no button

---

mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/CloseVaultButton.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailCollateralsRow.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailLoansRow.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetPayBackList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/PayLoanCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCard.tsx
mobile-app/cypress/e2e/functional/wallet/loans/loans.spec.ts
mobile-app/cypress/e2e/functional/wallet/loans/loans_with_dfi_dusd_vault_share.spec.ts
mobile-app/cypress/e2e/functional/wallet/loans/vault_detail.spec.ts
mobile-app/cypress/support/loanCommands.ts

chore(e2e): update vault details e2e

---

mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailLoansRow.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/PayLoanCard.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmPaybackLoanScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/cypress/e2e/functional/wallet/loans/loans.spec.ts
mobile-app/cypress/e2e/functional/wallet/loans/loans_unloop_dusd.spec.ts
mobile-app/cypress/support/loanCommands.ts

- Update e2e for unloop dusd loans 
Fixes #

chore(e2e): update e2e for unloop dusd loans 

---

mobile-app/app/screens/AppNavigator/screens/Loans/components/VaultCardStatus.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultCard.test.tsx.snap
mobile-app/cypress/e2e/functional/wallet/loans/loans_payback.spec.ts

- Fix failing e2e for payback loan
Fixes #

chore(e2e): update payback loan e2e

---

mobile-app/app/screens/AppNavigator/screens/Loans/VaultDetail/components/VaultDetailCollateralsRow.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/CollateralizationRatioDisplayV2.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/AddOrRemoveCollateralScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/cypress/e2e/functional/wallet/loans/collateral.spec.ts
mobile-app/cypress/support/loanCommands.ts

chore(e2e): update collaterals e2e

---

website/src/pages/api/v0/announcements.ts

chore(api): removed unused announcement

---

shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Added translation for "Get DFI" in the Portfolio Navigation page under the Receive Screen. For DE, FR, ZH-Hans, ZH-Hant
Fixes #

chore(translation): updated for get dfi

---

mobile-app/app/components/TokenDropdownButton.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertScreen.tsx
mobile-app/app/styles.json
mobile-app/app/tailwind.config.js
mobile-app/cypress/e2e/functional/wallet/portfolio/convert/convert.spec.ts
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

This PR is for updating the ConvertScreen UI to the latest design
Fixes #
1. updated ConvertScreen page 
2. added translations for ConvertScreen `TO RECEIVE`
3. updated e2e for convertscreen

feature(ui-ux): add new ui changes to convertscreen page

---

mobile-app/app/contexts/FeatureFlagContext.tsx
mobile-app/app/contexts/__mocks__/FeatureFlagContext.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/FeatureFlagScreen.test.tsx
shared/types/website.ts
website/src/pages/api/v0/settings/flags.ts

This PR to update the feature flag by adding a new type to enable app distinction between Mobile LW, Desktop LW, Scan etc.
Fixes #

feature(core): update feature flag

---

.github/CODEOWNERS
package-lock.json
package.json
website/.eslintrc
website/next-env.d.ts
website/package.json
website/src/components/commons/Container.tsx
website/src/components/layouts/Footer.tsx
website/tsconfig.json

chore(deps): update deps, cleanup webapp

---

docker-compose.yml
mobile-app/app/components/icons/assets/__snapshots__/index.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Loans/components/__snapshots__/VaultInfo.test.tsx.snap
package-lock.json
package.json

fix(rn-svg): crashing android

---

mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PoolPairCards.tsx

fix(ui-ux): fixed dex pool pair card price conversion to match with scan

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/OCG/DFIPDetailScreen.tsx

Fix MainNet DFIP proposal fee displayed to 50DFI
Fixes #

fix(core): dfip mainnet fee 50DFI

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx

- As titled, only exception is when paying back DUSD using collateral
Fixes #3904

fix(ui-ux): use oracle pricing as the price display during loan payback

---

mobile-app/app/api/transaction/dfi_converter.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

Added the missing DE/FR translations for MLW
- https://birthday.atlassian.net/browse/DW20DW-529
- https://birthday.atlassian.net/browse/DW20DW-301
- https://birthday.atlassian.net/browse/DW20DW-300
- https://birthday.atlassian.net/browse/DW20DW-383
- https://birthday.atlassian.net/browse/DW20DW-384
Fixes #

fix(translation): added missing translations

---

mobile-app/app/screens/AppNavigator/screens/Auctions/screens/AuctionsFaq.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/CfpDfipProposalsFaq.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokensVsUtxoFaq.tsx

Made the first dropdown active across all the FAQ Sections.
Initially, for Auction, UTXO & Tokens, & Governance, all dropdown sections were closed.
https://birthday.atlassian.net/browse/DW20DW-573
Fixes #

fix(ui-ux): made first dropdown active for FAQ (Auction, UTXO & Tokens, Governance)

---

mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts

chore(dex): dex stabilization fee

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TotalPortfolio.tsx

feat(ui-ux): add EUROC as currency in portfolio

---

mobile-app/app/screens/AppNavigator/screens/Dex/hook/DexStabilization.ts

- Display dex stab fee for EUROC
Fixes #
- Will check how to improve code

fix(ui-ux): display euroc stab fee

---

shared/translations/languages/it.json

chore(translations): updated it.json

---

mobile-app/app/contexts/FeatureFlagContext.tsx

fix(bug): prevent website down if flags are not available

---

mobile-app/cypress.config.js
mobile-app/cypress/e2e/functional/wallet/settings/serviceProvider.spec.ts
mobile-app/cypress/support/commands.ts

- Fix outdated data in service provider spec
- Added wait time to handle playground random delay to load in CI env
Fixes #

chore(e2e): service-provider-spec-fix

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/MarketplaceScreen.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/LiquidityMiningFaq.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/LiquidityMiningFaq.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

fix(ui-ux): changed Cake Defi to Bake

---

.github/workflows/ci-e2e.yml
mobile-app/cypress.config.js
mobile-app/cypress/e2e/functional/wallet/settings/serviceProvider.spec.ts
mobile-app/cypress/support/commands.ts

Fixed address book spec failure
Fixed service provider spec failure affected by address book fix
Reduced 10 containers to 8 
Fixes #

chore(e2e): address-book-spec-fix 

---

docker-compose.yml
package-lock.json
package.json

feature(evm): update jellyfish for transferdomain

---

mobile-app/app/screens/AppNavigator/BottomTabNavigator.tsx

feat(ui-ux): hide bottom nagivation when EMV network is selected

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/AddressBookScreen.tsx

chore(ui-ux): resolved ui bug for address book screen

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/BottomSheetAddressDetailV2.tsx

fix(ui-ux): copy evm address when evm domain is toggled on

---

docker-compose.yml
mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx

As titled. We can get the dynamic eth rpc url based on network from another open [pr](https://github.com/BirthdayResearch/defichain-wallet/pull/4009)
Fixes #

fix(ui-ux): fix send nonce and vm address

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenSelectionScreen.tsx

fix(core): updated token selection screen

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertScreen.tsx

fix(ui-ux): fix convert selection

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/CreateOrEditAddressLabelForm.tsx

Add checks if address label is trimmed
Add label validation check to disallow address label if its existing
Fixes #4042

fix(ui-ux): address book bottom sheet in portfolio page

---

mobile-app/app/components/icons/assets/index.ts

fix(core): fix feature branch conflict to 'main'

---

mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/contexts/EVMProvider.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/SwapTokenSelectionScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx

chore(core): refactored transfer domain provider

---

mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/components/TokenDropdownButton.tsx
mobile-app/app/components/icons/assets/index.ts
mobile-app/app/contexts/EVMProvider.tsx
mobile-app/app/screens/AppNavigator/screens/Auctions/screens/PlaceBidScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/SwapTokenSelectionScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/components/BottomSheetLoanTokensList.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/AddOrRemoveCollateralScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/BorrowLoanTokenScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/DFIBalanceCard.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TokenIcon.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/EvmTokenBalances.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenSelectionScreen.tsx

fix(chore): updated evm tokenId and fixed DFI evm icon and balance 

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx

fix(ui-ux): choose address by domain

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/AddOrEditAddressBookScreen.tsx

chore(ui-ux): hide address type selection if evm disabled

---

mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/components/SummaryTitle.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenSelectionScreen.tsx

fixed alignment of to address label
Fixes DFC-349, DFC-351

fix(ui-ux): fixed address title in address input screen

---

mobile-app/app/contexts/CustomServiceProvider.tsx

feat(ui-ux): update blockscout url

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/TokenBalance.ts

fix(core): fixed hang issue on click of denomination currency

---

mobile-app/app/contexts/CustomServiceProvider.tsx

feat(core): update testnet eth rpc url

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/AddressBookScreen.tsx

fix(ui-ux): fixed search unsaved address in addressbook screen

---

shared/contexts/StatsProvider.tsx

fix(chore):  fixed network icon issue on network change

---

mobile-app/app/contexts/EVMProvider.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/EvmTokenBalances.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx
shared/store/evm.ts

fix(core): fix send dvm to dvm txn

---

shared/store/evm.ts

fix(core): fix null data for evm wallet details

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/AddressBookScreen.tsx

fix(ui-ux): fixed address book label overlap issue for evm address

---

mobile-app/app/components/HeaderTitle.test.tsx
mobile-app/app/contexts/__mocks__/CustomServiceProvider.tsx
mobile-app/app/contexts/__mocks__/EVMProvider.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/DFIBalanceCard.test.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ReceiveScreen.test.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/__snapshots__/ReceiveScreen.test.tsx.snap

fix(core): fix unit test case

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenSelectionScreen.tsx

fix(ui-ux): hide Get DFI btn on empty portfolio screen

---

mobile-app/app/screens/AppNavigator/screens/Settings/components/CustomUrlInput.tsx

fix(core): fixed app crashing issue

---

mobile-app/app/contexts/EVMProvider.tsx

fix(core): fix invalid nonce error

---

mobile-app/app/contexts/EVMProvider.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/EvmTokenBalances.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenSelectionScreen.tsx

fix(ui-ux): fixed Send screen displays no assets displayed issue

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx

fix(ui-ux): hide swap btn for evm domain on token details screen

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/ServiceProviderScreen.tsx

chore(core): disallow http from custom service provider url

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TotalPortfolio.tsx

fix(ui-ux): hide loan related data on portfolio card

---

mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/EvmTokenBalances.ts

Properly convert amount into a string-number. BigNumber stores big decimals as exponential notation `0.00000005` into `5e-8`
Fixes DFC-372

fix(core): fix decimal value turning into exponential notation string

---

mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/contexts/CustomServiceProvider.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/PortfolioCard.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TokenNameText.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenSelectionScreen.tsx

This reverts commit df92ccc8a9436dc4fea9b566dca6cea8c70eab4e.
Fixes #

feat(ui-ux): remove duplicate `for EVM` text on token name

---

mobile-app/App.tsx
mobile-app/app/contexts/EVMProvider.tsx

feat(ui-ux): log error in evm provider

---

mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/EvmTokenBalances.ts
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx
shared/contexts/DeFiScanContext.tsx

feat(ui-ux): redirect token summary link to metascan for evm

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx

fix(ui-ux): display evm address as from on convert

---

mobile-app/app/contexts/EVMProvider.tsx

chore(logs): add info logs in evm provider

---

mobile-app/app/contexts/EVMProvider.tsx

feat(ui-ux): remove usememo in evm provider

---

mobile-app/cypress/e2e/functional/transferDomain/addresses.spec.ts
mobile-app/cypress/e2e/functional/wallet/settings/serviceProvider.spec.ts

chore(tests): test e2e runner

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
shared/store/userPreferences.ts

fix(ui-ux): handle empty wallet address

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertScreen.tsx

Added a check to see if target token has been selected before enabling 'Continue' button
Fixes #
DFC-389

fix(ui-ux): convert screen continue button

---

shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

chore(translations): add translation for dusd-loop collateral info

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertScreen.tsx

fix(ui-ux): fixed convert screen issue for evm domain

---

docker-compose.yml

chore(core): updated docker file

---

mobile-app/app/contexts/CustomServiceProvider.tsx

chore(core): added ethrpc url for main net

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/MarketplaceScreen.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/LiquidityMiningFaq.tsx
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/LiquidityMiningFaq.test.tsx.snap
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

chore(ui-ux): remove bittrex from exchange list

---

mobile-app/app/components/OceanInterface/OceanInterface.tsx

chore: update saveTx endpoint

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/TotalPortfolio.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/PortfolioCurrency.ts
mobile-app/cypress/e2e/functional/wallet/portfolio/portfolio.spec.ts

chore(ui-ux): remove usdt in denomination

---

.github/workflows/eas-update-provisioning-profile.yml

chore(ci): sync provisioning profile

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/EvmTokenBalances.ts

fix(ui-ux): show v1 token on EVM side

---

.github/workflows/eas-publish.yml

update(workflow): remove non-interactive build

---

.github/workflows/eas-publish.yml

Reverts BirthdayResearch/defichain-wallet#4191

Revert "update(workflow): remove non-interactive build"
