.github/workflows/defichain-dependencies.yml
docker-compose.yml
package-lock.json
package.json

1. bump defichain-dependencies to always stay on bleeding edge version with`>=` resolution
2. also updated whale & playground to use the latest docker version

bump defichain-dependencies to always stay on bleeding edge

---

translations/index.ts

/kind fix
Currently, `i18njs` behavior is to "guess" the missing translations. It is causing some issues with texts that contains punctuation marks. Also, it replaces camel case text with spaces which is an issue with some proper nouns (ex. WeChat -> We Chat). Reference - https://github.com/fnando/i18n-js#translation-missing-behaviour-control
Current behavior is to use the "text" as fallback if translation is missing.
Fixes #

Translations fix to prevent "guessing" results

---

hooks/api/useNetwork.ts
store/network.ts

/kind chore
This allows users to use playground without setting up their local version.

Added temporary remote playground

---

screens/AppNavigator/AppNavigator.tsx
screens/WalletNavigator/WalletNavigator.tsx
screens/WalletNavigator/screens/WalletMnemonicCreate.tsx
screens/WalletNavigator/screens/WalletMnemonicCreateVerify.tsx
screens/WalletNavigator/screens/WalletMnemonicRestore.tsx
screens/WalletNavigator/screens/WalletOnboarding.tsx

/kind feature
- This PR implementation of the wallet setup screens.
- The discord should focus on the functional UX and UI correctness. For major UI changes, please create tickets for iterative purposes.
- We need a good understanding of how the font looks on the different platforms. I mainly develop on iOS, without referencing Android.
- @izzycsy @thedoublejay to gather functional changes, narrative/copy, implementing e2e tests on the playground.
2 screens condensed into one, we want to introduce an extremely simple UX. Setting up multiple wallets is internally complex to implement and cognitively heavy for users to understand. Irrelevant for many users as people don't usually need multiple wallets. When we are to enable multiple wallets, mnemonic wallets are hierarchy deterministic by …

`Mnemonic Wallet` - Implementation

---

components/icons/tokens/_index.test.tsx
package-lock.json
package.json
screens/LoadingNavigator/LoadingScreen.test.tsx

/kind chore
Removed deprecated `react-native-testing-library` and replaced with `@testing-library/react-native`. See https://www.npmjs.com/package/react-native-testing-library
Fixes #

removed deprecated package `react-native-testing-library`

---

.github/governance.yml
.github/labeler.yml
.github/labels.yml

/kind chore
- Added more area labels for project governance
- Removed `screens/*` labels as it has no functional purpose in project governance as concern usually crosses between multiple screen

Added more area labels for project governance

---

constants/Theme.ts
hooks/design/useCachedResources.ts
screens/AppNavigator/BottomTabNavigator.tsx
screens/AppNavigator/screens/SettingsScreen/SettingsNavigator.tsx
screens/AppNavigator/screens/SettingsScreen/SettingsScreen.tsx
screens/WalletNavigator/screens/WalletMnemonicCreate.tsx
screens/WalletNavigator/screens/WalletOnboarding.tsx

/kind fix
Updated existing icon set to use MaterialIcons set.
Fixes #164 
- I am not a big fan of using Material on non-android devices, we should use a platform-agnostic icon set. We should change the icon set in the future.
- Did not use the MaterialCommunity set as it's not a superset of Material and the icons' name and style are not consistent with the original material guidelines.

updated all icons to use MaterialIcons set

---

cypress/integration/functional/balances.spec.ts
screens/AppNavigator/screens/BalancesScreen/BalancesNavigator.tsx
screens/AppNavigator/screens/BalancesScreen/BalancesScreen.test.tsx
screens/AppNavigator/screens/BalancesScreen/BalancesScreen.tsx
screens/AppNavigator/screens/BalancesScreen/__snapshots__/BalancesScreen.test.tsx.snap

/kind chore
- Added missing BalancesNavigator props
- Used MaterialIcons instead of Community which isn't natively cached
- Used `./components` instead of react-native for `Text`, `View` for future dark theme-ing
- Deprecated NumberText use
- Used explicit React Props for Navigation
- Used the correct separator design pattern
- Influence/use style from top-level flex concepts instead of individual styling flex items
- Removed the use of `testID` for each subcomponent, they should only be done at the root level component
- Instead of passing referencing into component, exposed a closure of non-side-effect coding
- Updated design to be more resilient towards screen fragmentation
@thedoublejay help me fix the tests and merge this PR in

clean up and reduced styles for Balances

---

app/storage.test.ts
app/storage.ts

/kind feature
Environment and network prefixed storage for network and environment-independent settings.
Created so that we don't accidentally leak secrets between evironments.

added environment and network prefixed storage

---

app/api/playground.test.ts
app/api/playground.ts
app/api/whale.test.ts
app/api/whale.ts
package-lock.json
package.json

/kind chore
Added `whale` and `playground` client that doesn't use the redux store to hold their state. With this, it allows for stateless/storeless use cases. This also moves app logic from UI logic.
Tests are written independently but not wiring with UI yet. stateless/storeless wallet will be written before wiring up the UI logic.

`whale` and `playground` client abstracted from UI logic

---

app/wallet/index.test.ts
app/wallet/index.ts
app/wallet/mnemonic.test.ts
app/wallet/mnemonic.ts
app/wallet/network.ts
app/wallet/whale.ts
package.json

/kind feature
Environment and network independent Wallet.
1. `useCachedWhaleClient()` to load whale client first
2. `useCachedWallet()` to load jellyfish wallet instance
3. `getWallet()` to get HD wallet
4. `getWallet().get(0)` to get default account
5. `getWallet().get(0).withTransactionBuilder()` to build transaction ready for broadcast
This is created to separate UI logic from the wallet to keep the UI state and UI implementation clean.
1. transaction sending after building transaction will be added at the global store, will create another PR for it.
2. wallet state for global refresh (change env/network) will be managed in the global store with a UUID for an automatic wallet refresh, will create another PR for it.

Environment and Network independent Wallet

---

.github/dependabot.yml
.github/workflows/expo-dependencies.yml

/kind chore
Let `dependabot.yml` manage `expo-cli` upgrade on a daily cycle.

moved expo-cli bumping to `dependabot.yml` for independent update cycle

---

.github/workflows/expo-dependencies.yml
.github/workflows/expo-preview.yml
.github/workflows/expo-publish.yml
.github/workflows/release-publish.yml

/kind fix
Expo github action renamed `expo-packager` to `packager`. 
Reference - https://github.com/expo/expo-github-action
It throws warnings on some of our GH actions https://github.com/DeFiCh/wallet/actions/runs/1036834784
Fixes #

updated `expo-packager` to `packager`

---

app/components/OceanInterface/OceanInterface.test.tsx
app/components/OceanInterface/OceanInterface.tsx
app/contexts/WalletAddressContext.tsx
app/hooks/wallet/TokensAPI.ts
app/screens/AppNavigator/screens/Balances/BalancesScreen.test.tsx
app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/ReceiveScreen.test.tsx
app/screens/AppNavigator/screens/Balances/screens/ReceiveScreen.tsx
app/screens/AppNavigator/screens/Dex/DexScreen.tsx
app/screens/PlaygroundNavigator/sections/PlaygroundUTXO.tsx
app/screens/PlaygroundNavigator/sections/PlaygroundWallet.tsx
app/screens/RootNavigator.tsx
app/store/wallet.test.ts
app/store/wallet.ts

wallet address context

---

app/screens/WalletNavigator/WalletNavigator.tsx
app/screens/WalletNavigator/screens/CreateWallet/PinCreation.tsx
app/screens/WalletNavigator/screens/RestoreWallet/RestoreMnemonicWallet.tsx
cypress/integration/functional/onboarding/createMnemonicWallet.spec.ts
cypress/integration/functional/onboarding/restore.spec.ts

/kind feature
Encrypt restored wallet. Followed with biometric enrolment.
Fixes #

`Encrypted Wallet` - restore

---

app/screens/TransactionAuthorization.tsx

Replace height with display css to control TransactionAuthorization show/hide
/kind fix
- To make sure the UI of the navigator is consistent across OS

fix height issue in navigator

---

App.tsx
app/contexts/WalletContext.tsx
app/screens/PlaygroundNavigator/PlaygroundScreen.tsx
app/screens/RootNavigator.tsx
app/store/index.ts

/kind refactor
- Added missing network deps for wallet, not really required use it's reset at WalletPersistence.
- Refactored `StoreProvider` to be memo-ed and nested within `WalletProvider`

refactor global `/store.ts` usage

---

app/screens/WalletNavigator/screens/RestoreWallet/RestoreMnemonicWallet.tsx

/kind fix
- Enable dictionary type assist when typing in restore wallet screen
Fixes #446

`restore` - type assist

---

app/api/wallet/provider/mnemonic_encrypted.ts
package-lock.json

/kind feature
Reduce encrypt/decrypt difficulty for reasonable UX
Fixes #422

`Scrypt Difficulty` - reduce encrypt/decrypt time

---

app/api/wallet/provider/mnemonic_encrypted.ts
app/api/wallet/provider/mnemonic_unprotected.test.ts
app/api/wallet/provider/mnemonic_unprotected.ts
app/screens/PlaygroundNavigator/sections/PlaygroundWallet.tsx

/kind refactor
Just a minor refactor, doesn't really changes anything. Required as network was nested in wallet_provider.

refactor out `Abandon23Playground` from wallet_provider

---

app/__snapshots__/environment.test.ts.snap
app/environment.ts

/kind chore
Ocean `TestNet` has been deployed successfully recently. This PR enabled TestNet on `environments.Production`.

enabled TestNet on `environments.Production`

---

app/components/HeaderTitle.tsx

/kind chore
To increase main/test net interval to 30,000

ConnectionStatus to use different interval, 3000 for playground, 30000 for main/test

---

app/components/SectionTitle.tsx
app/screens/AppNavigator/screens/Balances/__snapshots__/BalancesScreen.test.tsx.snap
app/screens/AppNavigator/screens/Balances/screens/__snapshots__/TokenDetailScreen.test.tsx.snap
app/screens/AppNavigator/screens/Settings/screens/__snapshots__/AboutScreen.test.tsx.snap
app/screens/AppNavigator/screens/Settings/screens/__snapshots__/CommunityScreen.test.tsx.snap

/kind feature
- To improve UI when scrolling in Dex screen
Fixes #497
Not tested on Android device

Add background color to SectionLabel

---

app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx

/kind fix
- To allow full visibility of address of recipient
- To allow user to access scan QR button function when address is long
Fixes #518
Tested on iPhone 12 and Pixel 3a

`send` - overflow long addresses in recipient address field

---

app/components/NumberTextInput.test.tsx
app/components/NumberTextInput.tsx
app/components/__snapshots__/NumberTextInput.test.tsx.snap
app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
app/screens/AppNavigator/screens/Balances/screens/SendScreen.tsx
app/screens/AppNavigator/screens/Dex/DexAddLiquidity.tsx
app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

/kind fix
(iOS) For locales that uses comma instead of period as decimal place, when using a keyboardType="numeric" they don't have a period for decimal but they have comma. Because of this, they cannot input decimal places and currently stuck on input fields as they will not be able to submit a form.
This fix allows them to enter via AlphaNumeric keypad in case their decimalSeparator is not a period. In future tickets, we need to support locale based Input and display.
Fixes #592

add fix for numeric keyboard

---

.github/workflows/ci-drift.yml
.github/workflows/ci-e2e.yml
.github/workflows/ci.yml
.github/workflows/expo-preview.yml

/kind chore
The playground containers take time to be ready, this PR moves the container init before npm install allowing for better performance and faster test time. Chopping off 30 seconds on average.
Also in this PR, prefixed CI to be `ci-*.yml` and set up workflow dispatch and cron for ci.

`ci-e2e.yml` to setup container and install npm concurrently

---

app/contexts/WalletPersistenceContext.tsx
app/screens/RootNavigator.tsx

/kind fix
1. On cold start and a wallet is created, there's a 1-2 seconds where the Onboarding screen is displayed before loading the balances page. 
Fixes #

prevent wallet flicker

---

.github/workflows/ci-e2e.yml
.github/workflows/ci.yml

/kind chore
ci.yml and ci-e2e.yml to always run on push main and '0 1 * * *' due to code coverage

ci.yml and ci-e2e.yml to always run on push main and '0 1 * * *'

---

app/screens/AppNavigator/screens/Balances/BalancesScreen.test.tsx
app/screens/AppNavigator/screens/Balances/BalancesScreen.tsx
app/store/ocean.test.ts
app/store/ocean.ts

/kind fix
- To fix ocean interface height from going back to initial height upon resetting wallet after changing passcode successfully
- Fixes #603
- Tested on iPhone 12 & pixel 3a emulator

`ocean interface` - incorrect size on change passcode

---

.eslintrc
.github/workflows/ci.yml
package.json

/kind refactor
Same lint style but using `eslint` runner by default for better IDE integration and customizable to expo defaults.

refactor to `npm run lint` instead of `npm run standard`

---

app/screens/WalletNavigator/screens/RestoreWallet/RestoreMnemonicWallet.tsx

/kind feature
1. Add a warning popup when user has a filled form in Restore Mnemonic page. This is to prevent accidental exit and restarting again
Fixes #

`restore` - add warning popup when exiting a filled form

---

app/api/wallet/mnemonic_storage.ts
app/screens/AppNavigator/screens/Settings/SettingsScreen.tsx
app/screens/AppNavigator/screens/Settings/screens/ConfirmPinScreen.tsx
app/screens/PlaygroundNavigator/sections/PlaygroundWallet.tsx
app/screens/WalletNavigator/screens/CreateWallet/EnrollBiometric.tsx
app/screens/WalletNavigator/screens/CreateWallet/PinConfirmation.tsx

/kind refactor
Refactor to `mnemonic_storage.ts` to use `entropyAsMnemonic` & `mnemonicAsEntropy`.
With this, the entropy will always be at 32 bytes, it will not require us to pad for encryption.

refactor to `mnemonic_storage.ts` to use `entropyAsMnemonic` & `mnemonicAsEntropy`

---

app/contexts/WalletContext.tsx
app/contexts/WalletNodeProvider.tsx
app/screens/PlaygroundNavigator/PlaygroundScreen.tsx
app/screens/RootNavigator.tsx
app/screens/TransactionAuthorization.tsx

/kind refactor
Added `WalletNodeContext` so that `TransactionAuthorization` doesn't use `WalletPersistence` layer for future evolving code reasons.
Thus this allow `TransactionAuthorization` to access provider data via `useWalletNodeContext()`.
```ts
const { data: providerData } = useWalletNodeContext()
```

Added `WalletNodeContext` so that `TransactionAuthorization` doesn't use Persistence layer

---

.imgbotconfig

/kind chore
`/cypress/**` images are part of cypress visual regression.

added `.imgbotconfig` to ignore cypress image snapshot

---

.github/workflows/ci-drift.yml
.github/workflows/ci-e2e.yml
.github/workflows/ci.yml
.github/workflows/eas-publish.yml
.github/workflows/expo-preview.yml
.github/workflows/expo-publish.yml
README.md

/kind chore
Usually, the old workflow run is discarded and rendered useless, this change will kill it immediately saving runner concurrency count to achieve faster throughput for workflow.

added github workflow concurrency to cancel in progress when new workflow is triggered

---

app/screens/AppNavigator/screens/Balances/screens/ConvertScreen.tsx
cypress/integration/functional/wallet/balances/convert/convert.spec.ts

/kind feature
- To auto deduct 0.1 DFI UTXO if user try to convert all UTXO to Token
Fixes #715 
- Added condition to block continue button if balance after convert is less than 0.1
- Added condition to set UTXO input amount 0 if user press on 50% or MAX button when UTXO balance is equal or less than 0.1
- Tested on iPhone 12 and pixel 3a emulator

`convert` - auto deduct 0.1 DFI UTXO when converting max amount

---

app/screens/AppNavigator/screens/Dex/PoolSwap/PoolSwapScreen.tsx

/kind fix
Currently, when doing pool swaps on mainnet. There are some cases where "continue" button is disabled. This is due to the fact that we're using a "max amount" for Token B. We have this behavior before because we're allowing input in TokenB (currently, it's disabled). 
There's a slight difference on the calculated amount and max amount causing it to be invalid. Since we're not allowing editing of Token B, we don't need maxAmount for it.
Fixes #728 
Fixes #689

disabled poolswap button - remove max amount for token B

---

.github/governance.yml
.github/labels.yml

/kind chore
OSS Governance Bot has the ability to automatically regex capture version and platform from issue conversations. 
The Version label will be captured from /releases hence only released builds will show up with a new label.

governance.yml to automate capturing of platform and version labels

---

mobile-app/app/contexts/LocalAuthContext.tsx
mobile-app/app/screens/PrivacyLock.tsx

/kind fix
Currently, local storage setting (Privacy Toggle) and Hardware Async are checked before we display the prompt. This fix waits for the two promises before displaying the contents. Needs to be fully tested on a standalone device.
Fixes #

Wait for Privacy lock and Storage to load

---

.idea/inspectionProfiles/Project_Default.xml

/kind chore
We should remove the eslint inspection profile on IDE. I personally think the eslint running on live mode is quite distracting to development seeing those errors. Most of the errors that are shown in the IntelliSense are usually always corrected when we commit due to lint-staged. On slower computers, it's just perhaps too expensive to run this operation concurrently when writing code.

removed .idea/inspectionProfiles

---

mobile-app/app/components/OceanInterface/TransactionError.tsx
mobile-app/cypress/integration/functional/wallet/balances/send.spec.ts

Temporarily use scroll view to see full message, will update when design is ready
/kind feature
- To display clearer error message to the user for un-mapped error message
Fixes #1612

`error message` - fallback to display message from API

---

mobile-app/app/screens/AppNavigator/screens/Loans/LoansNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/ConfirmPaybackLoanScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Loans/screens/PaybackLoanScreen.tsx
shared/translations/languages/de.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

And warning message only when paying back in excess
/kind feature
- To provide a solution for user to resolve moving loan balance due to interest accrued from additional block during the transaction
Fixes #1678

`payback loan` - allow to payback more than outstanding balance

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/components/PoolPairCards/PoolPairCards.tsx
shared/translations/languages/de.json
shared/translations/languages/fr.json

/kind chore
- To add translation for search input placeholder in dex screen
- To add translation for info section in `Your poolpair`
- To remove left padding of expand/hide button that cause misalignment when button overflow to newline
Fixes #2319

chore(translations): update search poolpair placeholder

---

.github/workflows/defichain-dependencies.yml
.github/workflows/oss-governance-bot.yml
.github/workflows/oss-governance-labeler.yml
.github/workflows/oss-governance-labels.yml
.github/workflows/release-drafter.yml

/kind chore
- Rename workflows related to "OSS Governance" into a single Workflow, renamed the job within to "Labels", "Labeler" and "Bot".
- Add `permissions:` for workflows to harden workflow security.
- Remov the use of `DEFICHAIN_BOT_GITHUB_TOKEN` for security hardening.
- Add `concurrency:` for workflows that requires it.
- Bump versions and migrate "OSS Governance Bot" to use the new org.

chore(workflows): cleanup workflow permissions and names

---

mobile-app/app/components/VersionText.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/AboutScreen.tsx
mobile-app/app/screens/WalletNavigator/screens/components/OnboardingCarousel.tsx

/kind feature
Display app version on welcome screen. Currently, there's no way to determine the app version if you're not on wallet context (e.g, About Screen)
Fixes #2703

welcome screen - display app version #2703

---

mobile-app/app/screens/AppNavigator/screens/Balances/components/DFIBalanceCard.tsx
mobile-app/app/screens/AppNavigator/screens/Balances/screens/TokenDetailScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
mobile-app/cypress/integration/functional/wallet/balances/tokenDetail.spec.ts

/kind feature
Reenable showing Token Detail page when clicking on DFI on the Portfolio page
Fixes #2395
This is my first sketch for enabling the Swap token option for DFI in the TokenDetail screen.
@thedoublejay please give your opinion.

token detail - reenable for DFI #2395

---

mobile-app/app/components/OceanInterface/OceanInterface.tsx
mobile-app/app/components/OceanInterface/TransactionError.tsx
mobile-app/app/components/OceanInterface/__snapshots__/TransactionError.test.tsx.snap

/kind feature
Expand error text in ocean interface if error message is too big. `onTextLayout` dose not work on desktop so for desktop this will show half error message with ellipses at the tail.
https://user-images.githubusercontent.com/53080940/170472822-265dc2d8-2c5b-4a27-93c8-5cd9db00fd72.mp4
Fixes #1500

feature(ui-ux): added expand btn to expand error text in ocean interface

---

mobile-app/app/screens/AppNavigator/screens/Dex/DexConfirmRemoveLiquidity.tsx

/kind feature
Fixes #2883
Only subtracting the reservedDfi value only if token-B is DFI and ensured that the shown value is at least 0.

Remove Liquidity - Negative value #2883

---

mobile-app/cypress/e2e/functional/wallet/settings/networkDetails.spec.ts
mobile-app/cypress/e2e/functional/wallet/settings/settings.spec.ts

Because of duplicate component in portfolio and setting headerRight
/kind fix
- To fix broken e2e that was introduced in PR #3195 , when `HeaderNetworkStatus` is added to portfolio's `headerRight` duplicated component is found in settings screen too, so need to pinpoint the exact one to use in e2e
Fixes #

fix(e2e): click on visible header network icon

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx

/kind chore
Auto scroll to top while switching between instant/future swap tabs. Similar to "Available pairs" and "Your pool pairs" in Dex screen
Fixes #

chore(ui-ux): auto scroll top when switch between instant/future swap tabs

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/SwapTokenSelectionScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/DexNavigator.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/hook/SwappableTokensV2.ts

The value is the reserve of the token
We are retrieving it in the poolpairs API by first occurence
DFI-dETH --> 17M DFI reserve
DFI-dBTC --> 67M DFI reserve
but the reserve differs on each poolpair and we may be displaying the incorrect value
To fix this issue, we will display the equivalent value of 1 tokenA in tokenB
If your From token is DFI
```
Value displayed = 0.00004454 dBTC // 1 DFI = 0.00004454 dBTC
```
Fixes #

feature(core): replace reserve with token b value equivalent

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/CompositeSwapScreenV2.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SwapSummary.tsx
mobile-app/app/screens/AppNavigator/screens/Dex/hook/FutureSwap.ts
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

- Display block countdown time and link block number to explorer in swap page 
- Reformat display time in confirm page 
Fixes #

feature(ui-ux): settlement block time display on swap and confirm v2

---

mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SlippageToleranceV2.tsx

- Remove the 0.00 placeholder because 0 is a valid slippage tolerance and might confuse the user
- User is allowed to click the Set button with empty input -> This will revert to previous custom slippage
Fixes #

fix(ui-ux): update x behaviour on slippage tolerance

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/TokenBestPath.test.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/TokenBestPath.ts

- I noticed that the `1 / estimatedReturn` formula for bToA only works on direct pairs. There's a big difference for composite swap. To fix it, bestPath API has been used for both aToB and bToA
Fixes #

fix(core): use best path on price rates calculation

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx

Fix DFI UTXO amount not being populated when entering swap screen from DFI token detail screen
Fixes #

fix(core): utxo amount not included in swap from token detail screen 

---

mobile-app/app/screens/AppNavigator/screens/Loans/LoansScreenV2.tsx

- Removes the material top tabs that causes the internal build to crash the whole loans screen
Fixes #

fix(ui-ux): fix build by using button group v2

---

mobile-app/app/components/themed/ThemedFlashList.tsx

- fix for crashing dex search
- estimatedItemSize should never be 0
Fixes #

fix(core): crashing DEX search

---

mobile-app/app/components/TransactionCard.tsx
mobile-app/app/components/__snapshots__/TransactionCard.test.tsx.snap

This PR fixes quick inputs pressed state 
Fixes #
1. added checks on user's onPressIn and onPressOut when onPressIn state becomes active and triggers background
2. updated margins and paddings for quickinput to reflect figma

fix(ui-ux): added onPress UI state for quick input

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/AddressRow.tsx
mobile-app/cypress/e2e/functional/wallet/portfolio/cfp_dfip.spec.ts

When submitting CFP, should only allow seed wallet address (local address), if not the continue button should be disabled. 
Fixes #

fix(ui-ux): cfp only allow seed wallet address

---

mobile-app/app/components/icons/assets/TwitterIcon.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/AboutScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/AboutScreen.test.tsx.snap

chore(ui-ux): updated twitter logo to its latest version

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/__snapshots__/DFIBalanceCard.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/AddressBookScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/__snapshots__/NetworkSelectionScreen.test.tsx.snap
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/CreateWalletGuidelines.test.tsx.snap
mobile-app/app/screens/WalletNavigator/screens/CreateWallet/__snapshots__/OnboardingNetworkSelectScreen.test.tsx.snap

fix(ui-ux): fix selection of whitelisted address that redirects to edit address

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreen.tsx

fix(ui-ux): utxo-evm bug

---

mobile-app/App.tsx
mobile-app/app/api/wallet/service_provider.ts
mobile-app/app/contexts/CustomServiceProvider.tsx
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

- Return default EVM and ETH RPC provider urls when EVM feature flag is disabled
- Add translations for updated Service Provider screen
Fixes #

feat(core): return default evm providers url when evm flag is disabled

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreen.tsx

Handle auto-conversion of UTXO into DFI token when user is sending to an EVM address, and has enough UTXO but not enough DFI token.
Fixes DFC-363

fix(core): handle auto-conversion of utxo to dfi token

---

mobile-app/app/api/transaction/transfer_domain.ts
mobile-app/app/contexts/CustomServiceProvider.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/ConvertConfirmationScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendConfirmationScreen.tsx

Issue with `Invalid nonce` still persists on Android devices, probably because of eth rpc provider not loading properly with context. Reverting to previous version wherein transfer domain function is not dependent on context.
Fixes DFC-364

fix(core): skip eth provider for transfer domain

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/hooks/TokenBalance.ts

fix(ui-ux): token name and logo incorrect in convert screen

---

mobile-app/app/screens/AppNavigator/screens/Loans/hooks/ValidateLoanAndCollateral.ts
mobile-app/app/screens/AppNavigator/screens/Loans/screens/AddOrRemoveCollateralScreen.tsx

Allow borrowing of dTokens when vault has 100% DUSD collateral
- Vault should have DFI collateral > 50% (of loan value) AND vault should NOT have any DUSD collateral
- Vault has 100% DUSD collateral (newly added when dusd-loop is enabled)
- Vault should have DFI collateral > 50% of loan value
- Vault should have DUSD collateral > 50% of loan value
Fixes #

feat(ui-ux): allow 100% dusd vault to borrow non-dusd tokens

---

mobile-app/app/components/SummaryTitle.tsx

fix(ui-ux): add linear gradient to from address on evm

---

mobile-app/app/screens/AppNavigator/screens/Loans/screens/AddOrRemoveCollateralScreen.tsx

Allow adding of DUSD collateral to a vault with active DUSD loan
- Vault should have DFI collateral > 50% (of loan value)
- Vault has 100% DUSD collateral (newly added when dusd-loop is enabled)
- Vault should have DFI collateral > 50% of loan value
- Vault should have DUSD collateral > 50% of loan value
- Adding of DUSD collateral to a vault with both DFI and DUSD collaterals should be allowed
- Adding of non-DUSD collateral to a vault with an active DUSD loan, containing 100% DUSD collateral should not be allowed
Fixes #4130

fix(ui-ux): allow adding of dusd collateral with active dusd loan

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/AddressRow.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/SendScreen.tsx

- Bug: Users are able to send to evm address even if evm + transferDomain feature is disabled via the flag
Fixes #

fix(ui-ux): fully disable send to evm

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/components/AddressRow.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/OCG/CFPDetailScreen.tsx

fix(ui-ux): cfp valid address warning

---

.github/CODEOWNERS
mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/ActionButtons.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/TokenDetailScreen.tsx

fix(ui-ux): hide send btn for evm domain

---

mobile-app/app/screens/AppNavigator/screens/Settings/screens/ServiceProviderScreen.tsx
shared/contexts/WalletDataProvider.tsx

fix(ui-ux): fixed address book forgets saved addresses when user switch to custom provider

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/PortfolioScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Portfolio/components/PortfolioCard.tsx

fix(core): fixed issue of tokens not showing in EVM domain

---

mobile-app/app/screens/AppNavigator/screens/Portfolio/screens/GetDFIScreen.tsx
mobile-app/app/screens/AppNavigator/screens/Settings/screens/ServiceProviderScreen.tsx
shared/contexts/WalletDataProvider.tsx

fix(ui-ux): show reset btn on service provider screen without edit

---

mobile-app/app/components/__snapshots__/PinTextInput.test.tsx.snap
mobile-app/app/screens/AppNavigator/screens/Dex/CompositeSwap/components/SlippageTolerance.tsx
mobile-app/cypress/e2e/functional/wallet/dex/swap/swap_instant_non_dfi.spec.ts
shared/translations/languages/de.json
shared/translations/languages/es.json
shared/translations/languages/fr.json
shared/translations/languages/it.json
shared/translations/languages/zh-Hans.json
shared/translations/languages/zh-Hant.json

fix(ui-ux): increased custom slippage range to 0 to 1000

---

mobile-app/app/components/BottomSheetInfo.tsx
mobile-app/app/components/BottomSheetWithNav.tsx
mobile-app/app/components/BottomSheetWithNavV2.tsx
mobile-app/app/screens/TransactionAuthorization/PasscodePrompt.tsx

- Possible fix on bottom sheet not opening on some devices
- There are cases wherein the battery is low or reduced motion is enabled, the bottom sheet is not opening at all
Fixes #

fix(ui): bottom sheet reduced motion
